// PL-300 bank, batch A: Get or connect to data, Profile and clean the data
const Q = require('./h.js');
module.exports = [
// ---------- get ----------
Q('get','single',1,'Gateways',
`Your Power BI Desktop report imports data from a SQL Server database hosted in your company's datacenter. After you publish the report, the semantic model must refresh every morning in the Power BI service. Several colleagues also publish models that use the same server. What should you configure?`,
[`An on-premises data gateway in standard mode`,`An on-premises data gateway in personal mode`,`A virtual network (VNet) data gateway`,`No gateway, because the Power BI service can reach any SQL Server directly`],0,
`The Power BI service runs in the cloud and needs a gateway to reach data sources inside a private network. A standard on-premises data gateway is installed once on a machine that can reach the server and can be shared by many users and semantic models.`,
[``,`Personal mode serves only the person who installed it and can't be shared, so colleagues couldn't use it.`,`A VNet data gateway reaches sources inside an Azure virtual network, not a server in your own datacenter.`,`The service can't reach servers inside a private network without a gateway.`],
`مصادر داخل شبكة الشركة تحتاج on-premises data gateway، واختر standard mode لو أكثر من شخص سيستخدمها.`,['gw']),

Q('get','single',1,'Gateways',
`A semantic model imports two sources: an Excel file stored in SharePoint Online and a table in Azure SQL Database that allows access from Azure services. You configure scheduled refresh in the Power BI service. Do you need an on-premises data gateway?`,
[`No. Both are cloud sources the service can reach directly`,`Yes, for the Excel file only`,`Yes, for the Azure SQL Database table only`,`Yes, for both sources`],0,
`Cloud sources such as SharePoint Online and Azure SQL Database (with public network access allowed) are reached directly by the Power BI service by using cloud connections. A gateway is required for sources inside a private network, such as an on-premises server or a local file share.`,
[``,`SharePoint Online is a cloud service. No gateway is needed.`,`Azure SQL Database is reachable from the service when it allows public or Azure service access.`,`Neither source sits behind a private network.`],
`المصادر السحابية مثل SharePoint Online وAzure SQL لا تحتاج gateway، الـ gateway فقط للمصادر داخل شبكة خاصة.`,['gw','refresh']),

Q('get','single',2,'Storage mode',
`You connect to a sales table with 2 billion rows in a SQL Server data warehouse. Managers need to see transactions within minutes of them being written, and the table is too large to import. There is no Microsoft Fabric capacity. Which storage mode should you use for the table?`,
[`DirectQuery`,`Import`,`Direct Lake`,`Dual`],0,
`DirectQuery leaves the data in the source and sends queries to it each time a visual loads, so results are as fresh as the source and model size isn't limited by memory. It fits very large tables and near real-time needs when the source can handle the query load.`,
[``,`Import copies the data into the model. It would be stale between refreshes and the table is too large to import.`,`Direct Lake needs Delta tables in OneLake and a Fabric capacity. The data lives in SQL Server and there's no Fabric capacity.`,`Dual acts as Import or DirectQuery depending on the query, but it still stores an imported copy, which isn't possible here.`],
`لو البيانات ضخمة جدًا وتحتاج أحدث قيمة من المصدر بدون Fabric، استخدم DirectQuery.`,['dq','storage']),

Q('get','single',2,'Storage mode',
`Your organization lands curated sales data as Delta tables in a Microsoft Fabric lakehouse. The workspace is on an F64 capacity. You need a semantic model that performs like Import mode but doesn't require copying the data into the model during refresh. Which storage mode should you choose?`,
[`Direct Lake`,`Import`,`DirectQuery`,`Dual`],0,
`Direct Lake reads Delta tables in OneLake straight into memory. Queries are answered by the same VertiPaq engine as Import, but a refresh (framing) only updates metadata, so there's no full data copy.`,
[``,`Import performs well but copies all the data at each refresh, which the requirement rules out.`,`DirectQuery sends queries to the source every time and is usually slower than Direct Lake or Import.`,`Dual still keeps an imported copy of the data.`],
`بيانات Delta في OneLake مع Fabric capacity؟ استخدم Direct Lake: أداء قريب من Import بدون نسخ البيانات.`,['dl','storage']),

Q('get','yesno',3,'Storage mode',
`You're comparing storage modes for a new semantic model.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`Direct Lake semantic models require a Microsoft Fabric capacity.`,`A Direct Lake on SQL analytics endpoint table that's based on a SQL view falls back to DirectQuery.`,`Import mode tables always show data changes in the source as soon as they happen.`],
[true,true,false],
`Direct Lake is only available on Fabric capacity SKUs. Direct Lake on SQL analytics endpoints falls back to DirectQuery when it can't read a Delta table directly, for example when the table is a SQL view. Import shows the data as of the last refresh.`,
[`Yes. Direct Lake licensing is Fabric capacity only.`,`Yes. Views aren't Delta tables, so Direct Lake on SQL falls back to DirectQuery.`,`No. Import data is a snapshot that updates only when the model refreshes.`],
`Direct Lake يحتاج Fabric capacity، والـ views في Direct Lake on SQL تتحول إلى DirectQuery، وImport يعرض البيانات حتى آخر refresh فقط.`,['dl']),

Q('get','single',1,'Shared semantic model',
`A certified semantic model named Sales Model is published in a workspace. You need to build a new report on it in Power BI Desktop without creating another copy of the data, so that every report uses the same measures. What should you do?`,
[`Get data from Power BI semantic models and select Sales Model (live connection)`,`Download the .pbix file of Sales Model and build the report inside it`,`Import the Sales Model tables into a new model by using the SQL Server connector`,`Export Sales Model to Excel and import the workbook`],0,
`Connecting to a published semantic model creates a live connection. The report reuses the model's tables, relationships and measures, and no data is copied, so there's one source of truth.`,
[``,`Downloading the .pbix creates a second copy of the model to maintain.`,`Re-importing the source creates a duplicate model and duplicate logic.`,`Exporting to Excel loses the model and creates a static copy.`],
`استخدم الـ semantic model المنشور عبر live connection بدل نسخ البيانات، حتى تبقى المقاييس موحدة.`,['livecon','sharedds']),

Q('get','single',2,'Composite model',
`You have a live connection report on a shared semantic model. You need to add a small Excel table of sales targets that exists only in your team and relate it to the model's Date table. What should you do?`,
[`Change the connection to a DirectQuery connection to the semantic model, then import the Excel table`,`Add the Excel table through Get data; live connections accept new imported tables automatically`,`Ask the model owner to remove the Date table`,`Create a calculated table that reads the Excel file`],0,
`A live connection can't add other sources. When you choose Make changes to this model, the connection becomes DirectQuery to the semantic model, creating a composite model where you can add imported tables and relationships.`,
[``,`In a pure live connection, Get data for other sources isn't available until you switch to a composite model.`,`That breaks the shared model for everyone and doesn't solve the need.`,`DAX calculated tables can't read files.`],
`لإضافة بيانات إلى live connection حوّله إلى DirectQuery على الـ semantic model (composite model) ثم أضف الجدول.`,['composite']),

Q('get','single',1,'Credentials',
`You published a report whose semantic model imports from a web API that uses a key. Scheduled refresh fails with the message that the data source credentials are missing or invalid. Where do you fix this?`,
[`Semantic model settings in the Power BI service, under Data source credentials`,`File > Options > Data load in Power BI Desktop`,`The report's Format pane`,`Workspace settings > License info`],0,
`Credentials that Power BI Desktop uses aren't published with the model. In the service, open the semantic model settings and edit the Data source credentials (or the gateway or cloud connection) so scheduled refresh can authenticate.`,
[``,`Desktop options only affect your local file.`,`The Format pane controls visual appearance.`,`License info doesn't store data source credentials.`],
`بيانات الدخول لا تُنشر مع التقرير، حدّثها من Semantic model settings > Data source credentials.`,['sched']),

Q('get','single',2,'Privacy levels',
`A query merges customer data from an on-premises SQL Server with a public web page of exchange rates. You want to make sure no customer data is ever sent to the web source while Power Query combines them. How should you set the privacy levels?`,
[`SQL Server: Organizational, web page: Public`,`SQL Server: Public, web page: Public`,`SQL Server: None, web page: None`,`Turn on Always ignore Privacy Level settings`],0,
`Privacy levels tell the Power Query engine which data can be combined and folded between sources. Marking the database Organizational and the web page Public stops organizational data from being sent to a public source.`,
[``,`Marking the database Public allows its data to flow into any source.`,`None means privacy levels aren't configured, so the isolation you need isn't guaranteed.`,`Ignoring privacy levels can expose sensitive data to other sources.`],
`اضبط Privacy levels: البيانات الداخلية Organizational والمصادر العامة Public حتى لا تتسرب بيانات الشركة.`,['privacy','pqprivacy']),

Q('get','single',2,'Parameters',
`You need to move a Power BI Desktop file from a test SQL Server to the production server without editing every query. What should you create?`,
[`A Power Query parameter for the server name, used in the source step of each query`,`A what-if parameter`,`A field parameter`,`A calculated column that stores the server name`],0,
`Power Query parameters store values such as a server or database name. Each query's source step references the parameter, so you change one value (in Desktop or in the service semantic model settings) to switch environments.`,
[``,`What-if parameters create a DAX table and measure for scenario analysis. They can't change a data source.`,`Field parameters let readers switch fields in visuals.`,`A calculated column is evaluated after load and can't control the connection.`],
`لتغيير السيرفر بسهولة استخدم Power Query parameter داخل خطوة Source.`,['params']),

Q('get','order',2,'Parameters',
`You want report consumers' semantic model to switch from the test database to production after you publish, without republishing the file. Which three actions should you perform in sequence?`,
[`In Power Query, create a text parameter named ServerName`,`Replace the hard-coded server in each query's Source step with ServerName`,`After publishing, change ServerName in the semantic model settings in the service, then refresh`,`Create a what-if parameter named ServerName`,`Add ServerName to a slicer on the report`],
[0,1,2],
`Create the parameter, reference it from each Source step, then after publishing edit the parameter value under the semantic model's Parameters settings and refresh.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`What-if parameters are DAX objects for scenarios and can't drive connections.`,`Power Query parameters aren't exposed as slicers and a slicer can't change the source.`],
`الخطوات: إنشاء parameter، استخدامه في Source، ثم تعديله من إعدادات الـ semantic model في الخدمة.`,['params']),

Q('get','multi',2,'Get data',
`You need to create a single query that combines the monthly CSV exports stored in one SharePoint Online folder. All files have the same columns. Which two actions should you take? Each correct answer presents part of the solution. Select TWO.`,
[`Use the SharePoint folder connector and point it at the site URL`,`Filter the file list to the target folder, then select Combine files`,`Use the Web connector once for each CSV file`,`Use the Folder connector with the SharePoint site URL`,`Import each file separately and use Merge queries`],
[0,1],
`The SharePoint folder connector lists every file in the site. Filter to the right folder and file type, then use Combine files, which builds a sample-file function and appends all files into one table.`,
[`Correct.`,`Correct.`,`One query per file doesn't scale and must be edited every month.`,`The Folder connector is for local or network folders, not SharePoint URLs.`,`Merge joins tables side by side. Files with the same columns need Append, which Combine files does.`],
`لدمج ملفات متشابهة من SharePoint استخدم SharePoint folder ثم Combine files.`,['append']),

Q('get','single',1,'Get data',
`A data source contains 20 columns, but your report needs only 6 of them. What is the best place to remove the other 14?`,
[`In Power Query, as early as possible in the query`,`In the Data view, by hiding the columns`,`In the report, by not using them in visuals`,`In DAX, by creating a calculated table with SELECTCOLUMNS`],0,
`Removing columns in Power Query means they're never loaded, which reduces model size and refresh time. Doing it early also helps query folding push the column selection to the source.`,
[``,`Hidden columns are still loaded and still take memory.`,`Unused columns are still loaded.`,`A calculated table adds a copy and doesn't remove the original columns.`],
`احذف الأعمدة غير المطلوبة في Power Query مبكرًا حتى لا تُحمّل أصلًا.`,['datared','folding']),

Q('get','single',2,'Query folding',
`A query against SQL Server has these steps: Source, Filtered rows (year = 2026), Removed columns, Added index column, Changed type. You need to know which steps are translated into SQL and run at the source. What should you do?`,
[`Look at the query folding indicators next to each step in the Applied steps pane`,`Open Performance Analyzer`,`Check the column quality bar`,`Look at the relationship view`],0,
`Power Query shows query folding indicators beside each applied step. They reveal where folding stops, for example at an Index column step, so you can reorder steps and keep more work at the source.`,
[``,`Performance Analyzer measures report visuals, not Power Query folding.`,`Column quality shows valid, error and empty percentages.`,`Model view shows relationships, not folding.`],
`مؤشرات query folding بجانب كل خطوة تبين أين يتوقف تنفيذ الخطوات في المصدر.`,['folding']),

Q('get','yesno',2,'Query folding',
`A Power Query query connects to Azure SQL Database.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`A Filtered rows step on a column can usually fold back to the source.`,`Adding an Index column typically stops query folding for the steps after it.`,`Query folding matters only for DirectQuery and has no effect on Import refresh time.`],
[true,true,false],
`Filters and column selection fold well to relational sources. An Index column has no SQL equivalent in most cases, so folding often stops there. Folding also speeds up Import refresh, because less data is transferred and processed.`,
[`Yes. Filters translate to a WHERE clause.`,`Yes. Index columns commonly break folding, so add them as late as possible.`,`No. Folding reduces the data transferred during Import refresh too, and incremental refresh relies on it.`],
`الفلترة تُطوى للمصدر عادة، وIndex column يوقف الطي، والطي مهم أيضًا لسرعة refresh في Import.`,['folding']),

Q('get','single',3,'Storage mode',
`A model uses a DirectQuery fact table and an imported Product dimension. Slicers on Product are slow because every filter must be combined with the DirectQuery table. You want Product queries to be answered from memory when possible and still join efficiently with the fact table at the source. Which storage mode should you set for Product?`,
[`Dual`,`Import`,`DirectQuery`,`Direct Lake`],0,
`Dual tables can act as Import or DirectQuery depending on the query. Queries that touch only Product use the in-memory copy, and queries joined with the DirectQuery fact table can be sent to the source together, avoiding limited relationships.`,
[``,`Import on the dimension creates a limited relationship to the DirectQuery fact table, which forces extra work.`,`DirectQuery on the dimension makes slicer queries always go to the source.`,`Direct Lake needs Delta tables in OneLake and a Fabric capacity.`],
`الجداول البعدية المرتبطة بجدول DirectQuery تُضبط غالبًا على Dual.`,['storage','composite']),

Q('get','single',1,'Get data',
`You receive a JSON file that contains nested records for orders and their line items. What is the first step to turn it into a table in Power Query?`,
[`Connect with the JSON connector, convert the list to a table, then expand the record columns`,`Use the Text/CSV connector and split by comma`,`Open it in the Web connector and use Pivot column`,`Use DAX PATH functions`],0,
`The JSON connector returns lists and records. Converting the top-level list to a table and then expanding the record and list columns flattens the structure into rows and columns.`,
[``,`Splitting JSON text by comma breaks nested structures.`,`Pivot doesn't flatten nested records.`,`PATH functions work with parent-child hierarchies, not JSON.`],
`ملف JSON: استخدم JSON connector ثم To table ثم Expand للأعمدة المتداخلة.`,['json']),

Q('get','single',2,'Get data',
`You need Power BI Desktop to refresh a local folder of files only on your computer while you test, and you don't have admin rights to install services. Later the model will be published for a team. Which statement is correct?`,
[`Personal mode gateway can serve your own refreshes, but the team model will need a standard gateway`,`A personal mode gateway can be shared with the team later`,`Local folders never need a gateway after publishing`,`A VNet gateway is required for local folders`],0,
`Personal mode runs under your account and serves only you. For shared, managed refresh of a team model, a standard on-premises data gateway is needed, installed on a machine that can reach the folder.`,
[``,`Personal mode can't be shared with other users.`,`A local or network folder is behind your network, so the service needs a gateway.`,`VNet gateways are for Azure virtual network sources.`],
`Personal gateway لك وحدك، أما التقارير المشتركة فتحتاج standard gateway.`,['gwp','gw']),

// ---------- clean ----------
Q('clean','single',1,'Profiling',
`In Power Query, the column quality bar shows that a CustomerID column is 100% valid. Later you find nulls in that column after load. What is the most likely reason?`,
[`Column profiling is based on the top 1,000 rows by default`,`Column quality ignores null values`,`Nulls are created by the relationship with the Customer table`,`The model changed the data type after load`],0,
`By default, the profiling tools in Power Query evaluate only the first 1,000 rows. Switch the status bar option to Column profiling based on entire data set to see the full picture.`,
[``,`Empty values are shown as Empty in column quality.`,`Relationships don't write nulls into columns.`,`Changing types doesn't turn valid IDs into nulls.`],
`أدوات الـ profiling تفحص أول 1000 صف افتراضيًا، غيّرها إلى entire data set.`,['profile']),

Q('clean','single',1,'Profiling',
`You need to see how many distinct and unique values a ProductCode column has, to confirm it can be used as a key. Which Power Query view gives you this directly?`,
[`Column distribution`,`Column quality`,`Query dependencies`,`Advanced editor`],0,
`Column distribution shows the count of distinct values (different values) and unique values (values that appear exactly once) for each column. A good key has distinct and unique counts equal to the row count.`,
[``,`Column quality shows valid, error and empty percentages, not distinct counts.`,`Query dependencies shows how queries reference each other.`,`The advanced editor shows M code.`],
`Column distribution يعرض عدد القيم distinct وunique لمعرفة صلاحية المفتاح.`,['profile']),

Q('clean','single',1,'Errors',
`A Sales Amount column has a few errors after changing its type to Decimal Number because some rows contain the text "N/A". Business users want those rows kept with an empty amount. What should you do?`,
[`Use Replace errors on the column and replace with null`,`Use Remove errors on the column`,`Change the type back to Text`,`Filter the column to remove blanks`],0,
`Replace errors swaps error values for a value you choose, such as null, and keeps the rows. Remove errors would delete the rows, which the users don't want.`,
[``,`Remove errors deletes the whole rows.`,`Text amounts can't be summed.`,`The errors aren't blanks, and filtering would remove rows.`],
`لإبقاء الصفوف مع قيمة فارغة استخدم Replace errors بـ null وليس Remove errors.`,['errors']),

Q('clean','single',2,'Errors',
`After a refresh, Power BI Desktop shows "Load completed with errors" and a link to View errors for a Date column. The source now sends dates in two formats. What is the best long-term fix?`,
[`Change the column type by using Using locale (or parse the text) so both formats convert, and handle any remaining errors`,`Ignore the message, because errors don't affect the model`,`Delete the Date column`,`Set the column type to Any`],0,
`Import errors mean some values couldn't be converted. Converting with the correct locale or parsing the text into proper dates fixes the root cause, then Replace errors or a conditional column handles true exceptions.`,
[``,`Rows with errors load as blanks and silently skew results.`,`The column is needed for time analysis.`,`Type Any prevents date functions and time intelligence.`],
`عالج أخطاء التاريخ بتحويل صحيح باستخدام Using locale ثم تعامل مع الاستثناءات.`,['errors','types']),

Q('clean','single',1,'Clean text',
`A City column contains values such as "dubai", " Dubai" and "DUBAI ". Visuals show three separate cities. Which two Power Query transformations fix this with the least effort?`,
[`Trim, then Capitalize Each Word`,`Clean, then Lowercase`,`Split column by delimiter, then Merge columns`,`Replace values three times`],0,
`Trim removes leading and trailing spaces and Capitalize Each Word gives consistent casing, so all variants become "Dubai".`,
[``,`Clean removes non-printable characters but not spaces, so " Dubai" stays different.`,`Splitting and merging doesn't normalize spaces or case.`,`Manual replacements break when new variants appear.`],
`لتوحيد النصوص: Trim ثم Capitalize Each Word.`,['types']),

Q('clean','yesno',2,'Nulls',
`You're cleaning a Discount column in Power Query.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`Replace values can replace null with 0 in a numeric column.`,`Fill down copies the last non-null value into the null cells below it.`,`Remove empty on a column filter removes rows where the column is null or an empty text value.`],
[true,true,true],
`Replace values accepts null as the value to find. Fill down fills nulls with the value above, which is common for report-style exports. Remove empty filters out null and empty values.`,
[`Yes. Type null in Value to find.`,`Yes. Fill down and Fill up propagate existing values into nulls.`,`Yes. It removes null and blank rows for that column.`],
`Replace values يستبدل null، وFill down ينسخ القيمة السابقة، وRemove empty يحذف الفراغات.`,['errors']),

Q('clean','single',2,'Data quality',
`A Customer dimension has duplicate CustomerID rows because the CRM export repeats customers with different LastModified dates. You need one row per customer, keeping the most recent version. What should you do in Power Query?`,
[`Sort by LastModified descending, add Table.Buffer, then Remove duplicates on CustomerID`,`Remove duplicates on CustomerID without sorting`,`Group by CustomerID and count rows`,`Use Keep duplicates on CustomerID`],0,
`Remove duplicates keeps the first row it finds. Sorting by the most recent date first and buffering the sorted table makes sure the kept row is the latest version. Grouping with Max of LastModified and merging back is another valid pattern.`,
[``,`Without sorting, the row kept is arbitrary.`,`Counting rows doesn't give you the latest attributes.`,`Keep duplicates returns only the repeated rows.`],
`لاختيار أحدث صف: رتّب تنازليًا حسب التاريخ ثم Remove duplicates على المفتاح.`,['pqbest']),

Q('clean','single',1,'Profiling',
`Where do you turn on Column quality, Column distribution and Column profile in Power Query Editor?`,
[`View tab, Data Preview group`,`Home tab, Transform group`,`Model view, Properties pane`,`File > Options > Report settings`],0,
`The data profiling options are check boxes in the Data Preview group of the View tab in Power Query Editor.`,
[``,`Transform holds transformations, not profiling views.`,`Model view doesn't show Power Query previews.`,`Report settings control report behavior.`],
`أدوات الـ profiling من تبويب View في Power Query Editor.`,['profile']),

Q('clean','single',2,'Unexpected values',
`Column profile for an Age column shows a minimum of -1 and a maximum of 999. The business confirms these are placeholder values for unknown ages. How should you handle them so averages are correct?`,
[`Replace -1 and 999 with null in Power Query`,`Replace them with 0`,`Leave them and use AVERAGE in DAX`,`Delete the Age column`],0,
`Placeholder values distort statistics. Replacing them with null marks them as unknown, and aggregation functions such as AVERAGE ignore blanks, so the results stay correct.`,
[``,`Zero is a real value and would pull the average down.`,`The placeholders would inflate and distort the average.`,`The column is still useful for valid rows.`],
`القيم الوهمية مثل -1 و999 استبدلها بـ null حتى لا تفسد المتوسطات.`,['profile']),

Q('clean','order',2,'Errors',
`A query fails to load because a few rows in a Price column contain text. You want to find the cause and then fix it without losing valid rows. Which three actions should you perform in sequence?`,
[`Turn on Column quality to see the error percentage for Price`,`Use Keep errors on a duplicate query to inspect the failing rows`,`In the main query, apply Replace errors on Price with null (or fix the source values)`,`Remove the Price column`,`Change the Price column type to Text in the final step`],
[0,1,2],
`First measure the problem with Column quality, then inspect the exact failing rows with Keep errors in a separate query, and finally fix the main query with Replace errors or a proper conversion.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`Removing the column loses needed data.`,`Text prices can't be summed.`],
`الخطوات: Column quality ثم Keep errors للفحص ثم Replace errors في الاستعلام الأساسي.`,['errors','profile']),

Q('clean','single',2,'Data quality',
`Two source systems code gender differently: one uses M and F, the other uses Male and Female. After appending them, you need consistent values. What is the most maintainable approach?`,
[`Create a small mapping table and merge it to translate codes to one standard value`,`Write a nested IF calculated column in DAX`,`Replace values manually in each visual`,`Create two separate slicers`],0,
`A mapping (lookup) table in Power Query centralizes the translation. New codes are handled by adding a row, and the model stays clean for every report.`,
[``,`A DAX column works but is harder to maintain and adds calculation after load.`,`Visual-level fixes don't fix the data.`,`Two slicers confuse users and don't fix the data.`],
`لتوحيد القيم استخدم جدول mapping ودمجه في Power Query.`,['merge']),

Q('clean','multi',2,'Data quality',
`You're profiling a new Orders table before building the model. Which two findings should you fix in Power Query before loading? Each correct answer presents a complete solution. Select TWO.`,
[`OrderID has fewer distinct values than rows, but it should be the table's unique key`,`OrderDate is stored as text in several formats`,`The table has 500,000 rows`,`The Amount column has a Currency format in the source`,`The table name is Orders`],
[0,1],
`A key that isn't unique causes relationship and totals problems, and dates stored as inconsistent text break time intelligence. Both are data quality issues to resolve before load. Row count, formats and names aren't problems by themselves.`,
[`Correct.`,`Correct.`,`500,000 rows is a normal size.`,`Formatting can be set in the model.`,`The name is fine.`],
`أصلح المفاتيح المكررة والتواريخ النصية قبل التحميل.`,['profile','types']),

Q('clean','single',3,'Errors',
`A custom column uses Number.From([Amount]) and fails on some rows. You want the column to return 0 for those rows without removing them. Which M expression should you use?`,
[`try Number.From([Amount]) otherwise 0`,`if [Amount] = null then 0 else [Amount]`,`Number.From([Amount]) ?? 0`,`Table.RemoveRowsWithErrors`],0,
`The try ... otherwise expression catches errors raised by an expression and returns the fallback value, so failed conversions become 0.`,
[``,`This handles null but not text values that fail to convert.`,`The ?? operator handles null, not errors.`,`That function removes the rows, which isn't wanted.`],
`لمعالجة أخطاء التحويل داخل عمود استخدم try ... otherwise.`,['errors']),

Q('clean','single',1,'Profiling',
`You need to see a histogram of values and statistics such as min, max, average and count of errors for one column. Which feature do you use?`,
[`Column profile`,`Column quality`,`Query diagnostics`,`Performance Analyzer`],0,
`Column profile shows detailed statistics and a value distribution chart for the selected column.`,
[``,`Column quality only shows valid, error and empty percentages.`,`Query diagnostics trace query evaluation, not column statistics.`,`Performance Analyzer measures visuals in reports.`],
`Column profile يعرض الإحصاءات والتوزيع لعمود واحد.`,['profile']),

Q('clean','yesno',2,'Import errors',
`A refresh in Power BI Desktop completes but warns that 12 rows have errors.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`The rows with errors are loaded, with the failing cells shown as blank.`,`Power Query can create an Errors query to show the failing rows.`,`The same rows will fail silently in the service without any indication.`],
[true,true,false],
`Cells that fail during load are loaded as blanks, and View errors creates a query that lists them. In the service, refresh history shows errors and warnings, so failures aren't silent.`,
[`Yes. The error cells become blank values in the model.`,`Yes. View errors creates an Errors in query group to inspect them.`,`No. Refresh history reports problems, and failing refreshes send notifications.`],
`صفوف الأخطاء تُحمّل كقيم فارغة ويمكن فحصها عبر View errors.`,['errors'])
];
