// PL-300 bank, batch B: Transform and load the data
const Q = require('./h.js');
module.exports = [
Q('transform','single',1,'Data types',
`A ProductCode column contains values such as 00125 and 00987. After load, the leading zeros disappear. What should you do?`,
[`Set the column's data type to Text in Power Query`,`Set the data type to Whole Number`,`Format the column with a custom format string in the model`,`Sort the column by another column`],0,
`Codes that look like numbers but aren't used for math should be Text. Converting to a number removes leading zeros, which changes the code itself.`,
[``,`Whole Number strips the leading zeros.`,`A format string changes display only and can't restore lost zeros.`,`Sorting doesn't change the values.`],
`الأكواد ذات الأصفار في البداية نوعها Text وليس رقم.`,['types']),

Q('transform','single',2,'Data types',
`You import a price column that should be summed with exact precision to 4 decimal places, for example currency amounts. Which data type is the best choice?`,
[`Fixed decimal number`,`Decimal number`,`Whole number`,`Text`],0,
`Fixed decimal number (currency) stores values with four digits after the decimal and avoids floating-point rounding issues in totals.`,
[``,`Decimal number is a floating-point type and can show tiny rounding differences.`,`Whole number drops the decimals.`,`Text can't be aggregated.`],
`المبالغ المالية الأفضل لها Fixed decimal number.`,['types']),

Q('transform','single',1,'Unpivot',
`A budget table has one row per region and one column per month (Jan, Feb, Mar and so on). You need one row per region and month with a Month column and an Amount column. What should you do?`,
[`Select the Region column and use Unpivot other columns`,`Select the month columns and use Pivot column`,`Use Transpose`,`Use Group by on Region`],0,
`Unpivot turns column headers into attribute values, producing a long table with Region, Attribute (month) and Value columns. Unpivot other columns keeps working when new month columns appear.`,
[``,`Pivot does the opposite: rows to columns.`,`Transpose swaps all rows and columns, which isn't the shape you need.`,`Group by aggregates rows but doesn't reshape columns.`],
`الأعمدة الشهرية تتحول إلى صفوف باستخدام Unpivot other columns.`,['unpivot']),

Q('transform','single',2,'Unpivot',
`Why is Unpivot other columns usually better than Unpivot columns (selected) for a monthly budget file that gets a new month column every month?`,
[`It unpivots every column except the ones you keep, so new month columns are included automatically`,`It runs faster on large files`,`It keeps the original column order`,`It also changes the data types to Date`],0,
`Unpivot columns hard-codes the selected column names in the M step. Unpivot other columns stores the columns to keep, so any new month column is unpivoted without editing the query.`,
[``,`Performance isn't the reason.`,`Column order isn't the difference.`,`Neither option changes types automatically.`],
`Unpivot other columns يلتقط الأعمدة الجديدة تلقائيًا.`,['unpivot']),

Q('transform','single',1,'Pivot',
`A table has columns Date, Metric and Value, where Metric contains Revenue, Cost and Units. You need separate Revenue, Cost and Units columns. What should you do?`,
[`Select Metric and use Pivot column with Value as the values column`,`Unpivot Metric`,`Transpose the table`,`Split Metric by delimiter`],0,
`Pivot column turns the distinct values of one column into new columns and fills them from the values column, aggregating if needed.`,
[``,`Unpivot does the opposite.`,`Transpose swaps the whole table.`,`Splitting text doesn't reshape rows into columns.`],
`لتحويل القيم إلى أعمدة استخدم Pivot column.`,['pivot']),

Q('transform','single',2,'Group by',
`You need a table of total sales and number of orders per customer from an order lines table, created in Power Query. What should you use?`,
[`Group by CustomerID with an advanced grouping: Sum of Amount and Count distinct of OrderID`,`Remove duplicates on CustomerID`,`Merge the table with itself`,`Pivot CustomerID`],0,
`Group by with the Advanced option lets you define several aggregations at once, such as a sum and a distinct count, returning one row per customer.`,
[``,`Removing duplicates keeps one row but doesn't aggregate.`,`A self-merge doesn't aggregate.`,`Pivoting customers into columns creates a wide, unusable table.`],
`للتجميع في Power Query استخدم Group by مع Advanced لعدة تجميعات.`,['groupby']),

Q('transform','single',1,'Append',
`You have three tables, Sales2024, Sales2025 and Sales2026, with the same columns. You need one Sales table. What should you do?`,
[`Append queries as new`,`Merge queries as new`,`Create relationships between the three tables`,`Use Pivot column`],0,
`Append stacks tables with the same structure one under another. Append queries as new keeps the originals and creates a combined query.`,
[``,`Merge joins tables side by side by matching keys.`,`Relationships don't combine rows.`,`Pivot reshapes columns.`],
`جداول بنفس الأعمدة تُدمج فوق بعض باستخدام Append.`,['append']),

Q('transform','single',1,'Merge',
`An Orders query has ProductID. A Products query has ProductID and Category. You need Category in Orders during data preparation. What should you do?`,
[`Merge Orders with Products on ProductID using a left outer join, then expand Category`,`Append Products to Orders`,`Unpivot Products`,`Create a calculated column with RELATED before load`],0,
`Merge performs a join. A left outer join keeps every order and brings matching columns from Products, which you then expand.`,
[``,`Append stacks rows, it doesn't look up values.`,`Unpivot reshapes columns.`,`RELATED is DAX, evaluated after load, and needs a relationship.`],
`لجلب عمود من جدول آخر استخدم Merge بـ left outer ثم Expand.`,['merge']),

Q('transform','single',2,'Merge',
`You need a list of customers in the Customers query who have never placed an order in the Orders query. Which join kind should you use when merging Customers with Orders on CustomerID?`,
[`Left anti`,`Left outer`,`Inner`,`Full outer`],0,
`A left anti join returns rows from the first table that have no match in the second table, which is exactly customers without orders.`,
[``,`Left outer returns all customers, with or without orders.`,`Inner returns only customers who have orders.`,`Full outer returns everything from both tables.`],
`العملاء بدون طلبات = Left anti join.`,['merge']),

Q('transform','yesno',2,'Merge',
`You're merging two queries in Power Query.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`Fuzzy matching can match "Contoso Ltd" with "Contoso Ltd." in a merge.`,`An inner join keeps rows from both tables even when they have no match.`,`You can merge on more than one column by selecting the columns in the same order in both tables.`],
[true,false,true],
`Fuzzy merge compares text by similarity and can match near duplicates. An inner join keeps only matching rows. Multi-column merges pair the selected columns in the order you select them.`,
[`Yes. Fuzzy matching uses a similarity threshold.`,`No. Inner join returns only rows with matches in both tables.`,`Yes. Select the key columns in matching order in both tables.`],
`Fuzzy merge يطابق النصوص المتشابهة، وInner join يعيد المتطابق فقط، ويمكن الدمج على أكثر من عمود.`,['merge']),

Q('transform','single',2,'Reference vs duplicate',
`You have a query named RawSales with 15 cleaning steps. You need two new queries, SalesByDay and SalesByStore, that both start from the cleaned RawSales, and any future fix to RawSales must flow to both. What should you create?`,
[`Two queries that Reference RawSales`,`Two queries that Duplicate RawSales`,`Two copies of the source file`,`Two calculated tables in DAX`],0,
`Reference creates a new query whose source is the output of RawSales, so changes to RawSales flow through. Duplicate copies all steps into an independent query, so later fixes wouldn't flow.`,
[``,`Duplicates copy the steps and become independent, so fixes wouldn't propagate.`,`Copying files duplicates work and sources.`,`Calculated tables happen after load and add model size.`],
`Reference يرث أي تعديل على الاستعلام الأصلي، أما Duplicate فنسخة مستقلة.`,['refq']),

Q('transform','single',2,'Reference vs duplicate',
`You referenced a staging query named StgCustomers from two other queries. StgCustomers is only an intermediate step and must not appear as a table in the model. What should you do?`,
[`Clear Enable load for StgCustomers`,`Delete StgCustomers`,`Hide StgCustomers in Report view`,`Clear Include in report refresh for StgCustomers`],0,
`Disabling load keeps the query available to other queries but doesn't create a table in the model, which reduces model size and clutter.`,
[``,`Deleting it breaks the two queries that reference it.`,`A hidden table is still loaded and uses memory.`,`Excluding it from refresh could leave dependent queries with stale data and it still loads as a table.`],
`الاستعلامات الوسيطة: ألغِ Enable load حتى لا تُحمّل كجداول.`,['pqbest']),

Q('transform','single',1,'Star schema',
`A single flat table contains order lines plus product name, product category, customer name and customer city repeated on every row. Following best practice for Power BI, how should you model it?`,
[`Split it into a Sales fact table and Product and Customer dimension tables related by keys`,`Keep one flat table for simplicity`,`Create one table per column`,`Create a separate table for each year`],0,
`A star schema separates numeric events (facts) from descriptive attributes (dimensions). It reduces duplication, makes filtering predictable and is the design Power BI is optimized for.`,
[``,`Flat tables repeat attributes, grow larger and make some calculations harder.`,`One table per column isn't a meaningful design.`,`Splitting by year makes analysis across years harder.`],
`الأفضل في Power BI: star schema بجدول حقائق وجداول أبعاد.`,['star']),

Q('transform','order',3,'Star schema',
`You're building a Product dimension from a flat Sales table in Power Query. Which three actions should you perform in sequence?`,
[`Reference the Sales query to create a new query named Product`,`Keep only the product columns and use Remove duplicates on ProductID`,`In the model, relate Product[ProductID] to Sales[ProductID] (one-to-many) and remove the descriptive product columns from Sales`,`Duplicate the Sales query and keep all columns`,`Create a many-to-many relationship on ProductName`],
[0,1,2],
`Start from the cleaned Sales output by referencing it, reduce it to unique products, then relate the dimension to the fact table on the key and drop the repeated attributes from the fact.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`Duplicating copies all steps and keeps every column.`,`Names aren't reliable keys and many-to-many isn't needed.`],
`الخطوات: Reference ثم إبقاء أعمدة المنتج وإزالة التكرار ثم علاقة واحد لمتعدد.`,['star','refq']),

Q('transform','single',2,'Keys',
`Two source systems both use numbers 1 to 5000 as CustomerID. After appending them into one Customer dimension, keys collide. What is the best way to create a unique key?`,
[`Add a column that combines the source system code and the CustomerID, and use it as the key in both the dimension and the fact`,`Remove duplicates on CustomerID`,`Use the customer name as the key`,`Add an Index column only in the dimension table`],0,
`A composite key such as SYS1-1234 is unique across systems and can be built the same way in the fact table so relationships match. A surrogate index is also valid only if the fact gets the same value through a merge.`,
[``,`Removing duplicates would drop real customers.`,`Names aren't unique or stable.`,`An index in the dimension alone doesn't exist in the fact, so the relationship can't be built.`],
`عند تعارض المفاتيح من أنظمة مختلفة: اصنع مفتاحًا مركبًا من كود النظام + المعرف.`,['star']),

Q('transform','single',1,'Columns',
`You need a FullName column from FirstName and LastName with a space between them, created in Power Query. Which option is the fastest?`,
[`Select both columns and use Merge columns with a Space separator`,`Split column by delimiter`,`Group by FirstName`,`Pivot LastName`],0,
`Merge columns (on the Add column or Transform tab) concatenates the selected columns with a separator of your choice.`,
[``,`Split does the opposite.`,`Group by aggregates rows.`,`Pivot reshapes values into columns.`],
`لدمج عمودين نصيين استخدم Merge columns مع فاصل.`,['columnfromex']),

Q('transform','single',2,'Columns',
`You need a column that extracts the year and quarter as text like "2026 Q3" from an OrderDate column, but you aren't sure how to write M. Which feature can build the column from a couple of typed examples?`,
[`Column from examples`,`Conditional column`,`Invoke custom function`,`Index column`],0,
`Column from examples lets you type the expected output for a few rows. Power Query infers the transformation and writes the M code for you.`,
[``,`A conditional column uses if-then rules, which don't fit a date-to-text transformation.`,`Custom functions must already exist.`,`An index column numbers rows.`],
`Column from examples يكتب لك الكود من أمثلة تكتبها.`,['columnfromex']),

Q('transform','single',2,'Semi-structured',
`A column contains values like {"color":"red","size":"M"} stored as text. You need Color and Size columns. What should you do?`,
[`Use Parse > JSON on the column, then expand the record`,`Split the column by comma`,`Use Transpose`,`Change the type to Record`],0,
`Parse JSON converts the text into a record, which you then expand into separate columns.`,
[``,`Splitting by comma leaves quotes and keys in the values.`,`Transpose swaps rows and columns.`,`You can't set a type to Record from the type menu. Parsing is required.`],
`نص بصيغة JSON داخل عمود: Parse JSON ثم Expand.`,['json']),

Q('transform','single',2,'Semi-structured',
`An Excel report export has a two-row header: the first row holds the month, the second row holds Actual or Budget under each month. What sequence usually turns it into a proper table?`,
[`Transpose, fill down the month column, merge the two header columns, transpose back, promote headers, then unpivot`,`Promote headers once and unpivot`,`Use Group by on the first column`,`Remove the first two rows`],0,
`Multi-row headers are handled by transposing so the header rows become columns, filling down the blank month cells, combining the two header columns into one name, transposing back and promoting headers. Then unpivot to get one row per month and type.`,
[``,`Promoting once loses the second header row.`,`Group by doesn't fix headers.`,`Removing the header rows loses the month and type information.`],
`العناوين المكونة من صفين: Transpose ثم Fill down ثم Merge ثم Transpose ثم Promote ثم Unpivot.`,['unpivot','pivot']),

Q('transform','yesno',2,'Loading',
`You're configuring how queries load in Power BI Desktop.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`A query with Enable load cleared can still be referenced by other queries.`,`Clearing Include in report refresh stops the table from refreshing when you select Refresh.`,`A query with Enable load cleared still appears in the Data pane of the report.`],
[true,true,false],
`Disabled queries still run when other queries reference them but aren't loaded into the model, so they don't appear in the Data pane. Include in report refresh controls whether a loaded table refreshes during a model refresh.`,
[`Yes. It remains available as a source for other queries.`,`Yes. The table keeps its last loaded data during refresh.`,`No. It isn't loaded, so it doesn't appear in the model.`],
`Enable load يتحكم بالتحميل للنموذج، وInclude in report refresh يتحكم بالتحديث.`,['pqbest']),

Q('transform','multi',2,'Star schema',
`You're designing a sales model. Which two columns belong in the Sales fact table rather than in a dimension? Each correct answer presents a complete solution. Select TWO.`,
[`SalesAmount`,`OrderQuantity`,`ProductColor`,`CustomerCity`,`CategoryName`],
[0,1],
`Fact tables store measurable events and keys. Amounts and quantities are facts. Colors, cities and category names describe entities and belong in dimensions.`,
[`Correct.`,`Correct.`,`Product attributes belong in the Product dimension.`,`Customer attributes belong in the Customer dimension.`,`Category belongs in the Product dimension.`],
`الأرقام القابلة للجمع في جدول الحقائق، والأوصاف في الأبعاد.`,['star']),

Q('transform','single',3,'Semi-structured',
`A web API returns a JSON list of orders where each order has a nested list of line items. You need one row per line item with the order number repeated. What is the correct approach after converting the orders list to a table?`,
[`Expand the order record, then expand the line items list to new rows, then expand the line item records`,`Expand the line items list to comma-separated values`,`Transpose the table`,`Use Group by on order number`],0,
`Expanding a list column to new rows creates one row per list element while keeping the parent columns such as the order number. Then expand each line item record into columns.`,
[``,`Extracting values into one text cell loses the row structure.`,`Transpose doesn't flatten nested lists.`,`Group by aggregates, it doesn't flatten.`],
`القوائم المتداخلة: Expand to New Rows ثم Expand للسجلات.`,['json']),

Q('transform','single',1,'Transpose',
`A small settings table from Excel has field names in the first column and values in the second column, but you need the field names as column headers. What should you do?`,
[`Transpose the table, then Use first row as headers`,`Unpivot all columns`,`Pivot the second column`,`Group by the first column`],0,
`Transpose turns rows into columns. After transposing, the field names are in the first row, so you promote them to headers.`,
[``,`Unpivot makes the table longer, not wider.`,`Pivoting the second column would turn the values, not the field names, into headers.`,`Group by aggregates rows.`],
`لقلب الصفوف إلى أعمدة: Transpose ثم Use first row as headers.`,['pivot']),

Q('transform','single',2,'Group by',
`In Power Query you grouped Sales by Region with the operation All rows, creating a nested Rows column. What can you do with it next?`,
[`Add a custom column that works on each nested table, for example to rank or get the top row per region`,`Nothing, All rows can't be used`,`Load it directly as a relationship`,`Use it only in DAX`],0,
`All rows keeps the detail rows for each group as a nested table. Custom columns can process each nested table (for example, Table.Max or adding an index) before expanding the results.`,
[``,`All rows is a powerful pattern for per-group logic.`,`Nested tables can't become relationships.`,`Nested tables must be expanded before load.`],
`Group by مع All rows يسمح بعمليات على كل مجموعة مثل أعلى صف لكل منطقة.`,['groupby']),

Q('transform','single',2,'Dimensions',
`You need a Date dimension with every date from 1 January 2024 to 31 December 2027, created in Power Query so it's available to all tables. Which approach works?`,
[`Create a blank query with List.Dates, convert it to a table, then add Year, Month and other columns`,`Use Group by on the Sales date column`,`Use Remove duplicates on the Sales date column only`,`Unpivot the Sales table`],0,
`List.Dates builds a complete, contiguous list of dates, which is required for a proper date table. Extracting unique dates from Sales would miss days without sales.`,
[``,`Grouping sales dates skips days with no sales.`,`Unique sales dates also leave gaps.`,`Unpivot doesn't create dates.`],
`جدول تاريخ كامل بدون فجوات: List.Dates في Power Query أو CALENDAR في DAX.`,['datetbl'])
];
