// PL-300 bank, batch C: Design and implement a data model
const Q = require('./h.js');
module.exports = [
Q('design','single',1,'Relationships',
`A Product table has one row per ProductID. A Sales table has many rows per ProductID. What cardinality should the relationship have?`,
[`One-to-many (Product to Sales)`,`Many-to-many`,`One-to-one`,`Many-to-one from Product to Sales`],0,
`The dimension side (Product) has unique keys and the fact side (Sales) repeats them, so the relationship is one-to-many from Product to Sales.`,
[``,`Many-to-many is only needed when neither side has unique values.`,`One-to-one means both sides are unique, which Sales isn't.`,`The "one" side is Product, not Sales.`],
`البعد (قيم فريدة) إلى الحقائق (قيم مكررة) = One-to-many.`,['rel']),

Q('design','single',2,'Cross-filter direction',
`Your model has Product related to Sales (one-to-many, single direction). A slicer on Sales[Channel] must filter a visual that lists products. What's the recommended approach that avoids ambiguity?`,
[`Use a measure that counts sales rows and filter the product visual where the measure isn't blank`,`Set every relationship in the model to Both directions`,`Create a many-to-many relationship`,`Duplicate the Product table`],0,
`Bi-directional filters can cause ambiguity and slower queries. Filtering the product visual by a measure based on Sales (for example, Sales rows is not blank) achieves the same result while keeping single-direction relationships.`,
[``,`Setting all relationships to Both creates ambiguous filter paths and hurts performance.`,`Many-to-many isn't needed for a one-to-many key.`,`Duplicating Product doesn't make Sales filter it.`],
`تجنب Both direction قدر الإمكان، واستخدم مقياسًا لفلترة الأبعاد من جدول الحقائق.`,['bidi']),

Q('design','yesno',2,'Cross-filter direction',
`You're reviewing relationship settings.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`In a one-to-many relationship with single cross-filter direction, filters flow from the one side to the many side.`,`Bi-directional filtering is required for row-level security to reach the fact table from a dimension.`,`A one-to-one relationship always filters in both directions.`],
[true,false,true],
`Single direction filters from the dimension to the fact. RLS on a dimension already reaches the fact through a one-to-many relationship. One-to-one relationships always use both directions.`,
[`Yes. That's the default and recommended direction.`,`No. RLS on a dimension filters the related fact rows through the normal one-to-many direction. Bi-directional RLS is only needed in special cases.`,`Yes. One-to-one relationships are always bi-directional.`],
`الفلترة الافتراضية من البعد للحقائق، وRLS على البعد يصل للحقائق بدون Both.`,['rel','rlsg']),

Q('design','single',2,'Role-playing dimension',
`Sales has OrderDate, ShipDate and DueDate. There's one Date table. You created three relationships; one is active and two are inactive. You need a measure that shows sales by ship date. What should you use?`,
[`CALCULATE([Sales], USERELATIONSHIP(Sales[ShipDate], 'Date'[Date]))`,`RELATED('Date'[Date])`,`Make all three relationships active`,`CROSSFILTER with Both`],0,
`Only one relationship between two tables can be active. USERELATIONSHIP activates an inactive relationship for the duration of the CALCULATE, which is the standard way to use a role-playing date dimension.`,
[``,`RELATED fetches a value in row context; it doesn't change which relationship filters.`,`Only one active relationship is allowed between the same two tables.`,`CROSSFILTER changes direction, not which relationship is used.`],
`البعد متعدد الأدوار: علاقة واحدة نشطة والباقي عبر USERELATIONSHIP داخل CALCULATE.`,['userel','star']),

Q('design','single',2,'Role-playing dimension',
`Report authors in your company find USERELATIONSHIP measures confusing. They want to slice by Order Date and Ship Date at the same time in the same visual. What model design supports this?`,
[`Create a second date table (Ship Date) related to Sales[ShipDate] as an active relationship`,`Add a Both direction filter on the Date relationship`,`Hide the Date table`,`Create a calculated column with USERELATIONSHIP`],0,
`Separate role-playing dimension tables (Order Date and Ship Date), each with its own active relationship, let users filter by both dates at once without special measures.`,
[``,`Direction doesn't create a second role.`,`Hiding the table removes filtering.`,`USERELATIONSHIP only works inside CALCULATE in measures.`],
`للتصفية بتاريخين معًا: جدولي تاريخ منفصلين لكل دور.`,['star']),

Q('design','single',1,'Date table',
`You created a Date table with CALENDAR. Time intelligence functions such as TOTALYTD must use it. What should you do?`,
[`Mark it as a date table and select its Date column`,`Rename it to Calendar`,`Hide it`,`Set its storage mode to Dual`],0,
`Marking a table as a date table tells Power BI which column holds the dates. It validates the column (unique, no blanks, contiguous) and makes time intelligence use your table instead of automatic date tables.`,
[``,`The table's name doesn't matter.`,`Hiding doesn't define it as a date table.`,`Storage mode is unrelated.`],
`جدول التاريخ يجب تعليمه Mark as date table.`,['markdate']),

Q('design','multi',2,'Date table',
`Which two requirements must a column meet before you can mark its table as a date table? Each correct answer presents a complete solution. Select TWO.`,
[`It contains unique values with no blanks`,`It contains contiguous dates covering full years with no gaps`,`It must be named Date`,`It must be in DirectQuery mode`,`It must include a time portion`],
[0,1],
`The date column must be of type Date or Date/Time, have unique values, contain no blanks and have no missing dates in the range. Its name and storage mode don't matter.`,
[`Correct.`,`Correct.`,`Any column name is allowed.`,`Any storage mode is allowed.`,`A time portion isn't required; dates at midnight are typical.`],
`شروط جدول التاريخ: قيم فريدة بدون فراغات، وتواريخ متصلة بلا فجوات.`,['markdate','datetbl']),

Q('design','single',2,'Date table',
`Your model has 12 date columns across several tables, and the file size is larger than expected. You already have a proper Date table. What setting should you change?`,
[`Turn off Auto date/time for the file`,`Turn on Auto date/time`,`Change every date column to Text`,`Mark every table as a date table`],0,
`Auto date/time creates a hidden date table for every date column, which inflates the model. With a dedicated Date table, turn it off in File > Options > Current file > Data load.`,
[``,`That's what causes the hidden tables.`,`Text dates break time intelligence.`,`Only one table should be the date table.`],
`عند وجود جدول تاريخ خاص أوقف Auto date/time لتقليل حجم النموذج.`,['autodt']),

Q('design','single',1,'Properties',
`A Month Name column sorts alphabetically (April, August, December). You need calendar order. What should you do?`,
[`Set Sort by column on Month Name to a Month Number column`,`Change Month Name to a Date type`,`Sort the visual by value`,`Add a leading number to each month name`],0,
`Sort by column tells Power BI to order one column by the values of another column, such as MonthNumber 1 to 12.`,
[``,`Month names aren't dates.`,`Sorting by value orders by the measure, not the calendar.`,`Adding numbers changes the displayed names.`],
`لترتيب أسماء الشهور زمنيًا استخدم Sort by column برقم الشهر.`,['sortby']),

Q('design','yesno',2,'Properties',
`You're configuring column properties in Model view.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`Setting a City column's Data category to City helps map visuals place it correctly.`,`Setting Summarize by to None stops a Year column from being summed when added to a visual.`,`Hiding a column in Report view also removes it from the model's memory.`],
[true,true,false],
`Data category gives geographic and URL hints to visuals. Summarize by None prevents default aggregation of numeric columns such as Year. Hidden columns are still loaded; they're just not shown in the Data pane.`,
[`Yes. Geographic categories improve map geocoding.`,`Yes. The column will be grouped, not summed.`,`No. Hidden columns still use memory. Remove them in Power Query to save space.`],
`Data category للخرائط، وSummarize by None لمنع جمع عمود السنة، والإخفاء لا يقلل الذاكرة.`,['hier']),

Q('design','single',2,'Calculated column vs measure',
`You need each customer classified as Small, Medium or Large based on the customer's lifetime sales, and the class must be usable in a slicer. What should you create?`,
[`A calculated column in the Customer table`,`A measure`,`A visual calculation`,`A quick measure`],0,
`Slicers and axes need columns. A calculated column is evaluated for each customer row at refresh time and stored, so it can be used to slice and group.`,
[``,`Measures can't be placed in slicers.`,`Visual calculations live on one visual and can't be used as slicers.`,`Quick measures create measures.`],
`للتقسيم في Slicer تحتاج عمودًا (calculated column) وليس مقياسًا.`,['calcopts']),

Q('design','single',2,'Calculated tables',
`You need a table listing the top 10 products by sales at refresh time, used for a separate relationship-free analysis page. Which option fits best?`,
[`A calculated table using TOPN`,`A measure using TOPN`,`A calculated column using TOPN`,`A Power Query parameter`],0,
`A calculated table is evaluated at refresh and stores rows in the model, so it can hold a static top-10 list. Measures return scalar values and calculated columns add values to an existing table.`,
[``,`Measures return single values, not tables in the model.`,`A calculated column can't create new rows.`,`Parameters store single values.`],
`لإنشاء جدول من DAX وقت الـ refresh استخدم calculated table.`,['calcopts']),

Q('design','single',3,'Many-to-many',
`A Budget table is at Category and Month grain, while Sales is at Product and Date grain. You need Budget and Sales in the same visual by Category and Month. What's the recommended design?`,
[`Relate Budget to Category and Month dimension tables (or bridge tables) so both facts share dimensions at the right grain`,`Create a direct many-to-many relationship between Budget and Sales`,`Merge Budget into Sales`,`Use bi-directional filters on every relationship`],0,
`Facts at different grains should connect through shared dimensions at the level they both support. A dimension (or a bridge) for Category and for Month lets filters flow to both facts.`,
[``,`Relating two fact tables directly is ambiguous and not recommended.`,`Merging duplicates budget values on every sales row.`,`Bi-directional filters everywhere cause ambiguity.`],
`جداول حقائق بمستويات مختلفة تُربط عبر أبعاد مشتركة بالمستوى المناسب.`,['m2m','star']),

Q('design','single',2,'Hierarchies',
`Users want to drill from Category to Subcategory to Product in visuals. What should you create in the model?`,
[`A hierarchy in the Product table with Category, Subcategory and Product levels`,`Three separate slicers`,`A calculated table for each level`,`A bookmark`],0,
`A hierarchy groups columns into levels. Visuals can then drill down and up through the levels without adding fields one by one.`,
[``,`Slicers filter but don't provide drill-down.`,`Separate tables break the natural path.`,`Bookmarks capture states, not drill paths.`],
`للـ drill down أنشئ hierarchy في جدول البعد.`,['hier']),

Q('design','single',1,'Properties',
`You want users to find measures quickly. What property groups related measures into folders in the Data pane?`,
[`Display folder`,`Description`,`Synonyms`,`Data category`],0,
`Display folders organize measures and columns into folders in the Data pane without changing the model.`,
[``,`Descriptions appear as tooltips on hover.`,`Synonyms help Q&A and Copilot understand terms.`,`Data category helps visuals interpret values.`],
`Display folder لتنظيم المقاييس في مجلدات.`,['hier']),

Q('design','single',3,'Relationships',
`You create a relationship between Customer[CustomerID] and Sales[CustomerID], but Power BI sets it to many-to-many. You expected one-to-many. What's the most likely cause?`,
[`Customer[CustomerID] contains duplicate values (or blanks repeated)`,`Sales[CustomerID] contains duplicates`,`The columns have different names`,`Auto date/time is turned on`],0,
`For one-to-many, the one side must be unique. If Power BI detects duplicates in Customer[CustomerID], it can't create one-to-many. Fix the duplicates in Power Query.`,
[``,`Duplicates on the many side are expected.`,`Column names don't have to match.`,`Auto date/time doesn't affect this relationship.`],
`لو ظهرت many-to-many بدل one-to-many فغالبًا المفتاح في جدول البعد مكرر.`,['rel']),

Q('design','yesno',3,'Calculation options',
`You're deciding between calculated columns, measures and visual calculations.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`Measures are calculated at query time and respond to filters and slicers.`,`Calculated columns are recalculated each time a slicer changes.`,`A visual calculation can refer only to fields that are in its visual.`],
[true,false,true],
`Measures are evaluated at query time in the filter context. Calculated columns are computed at refresh and stored. Visual calculations run on the visual's data and can only reference fields placed on that visual.`,
[`Yes.`,`No. Calculated columns are computed during refresh and don't change with slicers.`,`Yes. Add a field to the visual first if the calculation needs it.`],
`المقاييس وقت الاستعلام، والأعمدة المحسوبة وقت الـ refresh، وVisual calculation تشير فقط لحقول الـ visual.`,['calcopts','visualcalc']),

Q('design','single',2,'Properties',
`A semantic model will be used by Copilot and Q&A. Users type "revenue" but the measure is named Net Sales Amount. What should you add to improve results?`,
[`Synonyms (and a description) on the Net Sales Amount measure`,`A display folder named Revenue`,`A second measure named Revenue that returns the same value`,`A Data category of Currency`],0,
`Synonyms map business terms to model objects for Q&A and Copilot, and descriptions give extra context. This avoids duplicate measures.`,
[``,`Folders organize the Data pane but aren't used as names.`,`Duplicate measures create maintenance issues.`,`Data category doesn't map words to measures.`],
`أضف Synonyms ووصفًا للمقاييس حتى يفهمها Q&A وCopilot.`,['copilotov'])
];
