// PL-300 bank, batch D: Create model calculations by using DAX
const Q = require('./h.js');
module.exports = [
Q('dax','single',1,'Aggregation',
`You need a measure that returns total revenue, where each Sales row has Quantity and UnitPrice columns and there's no Amount column. Which DAX expression is correct?`,
[`Revenue = SUMX(Sales, Sales[Quantity] * Sales[UnitPrice])`,`Revenue = SUM(Sales[Quantity]) * SUM(Sales[UnitPrice])`,`Revenue = SUM(Sales[Quantity] * Sales[UnitPrice])`,`Revenue = AVERAGEX(Sales, Sales[Quantity] * Sales[UnitPrice])`],0,
`SUMX iterates the table, multiplies quantity by price for each row, then sums the results. Multiplying two totals gives a wrong number.`,
[``,`The product of two sums isn't the sum of products.`,`SUM accepts a single column, not an expression.`,`AVERAGEX returns an average, not a total.`],
`لجمع حاصل ضرب عمودين لكل صف استخدم SUMX.`,['stat']),

Q('dax','single',1,'Aggregation',
`You need the number of different customers who bought something, from Sales[CustomerID]. Which function should you use?`,
[`DISTINCTCOUNT(Sales[CustomerID])`,`COUNT(Sales[CustomerID])`,`COUNTROWS(Sales)`,`COUNTA(Sales[CustomerID])`],0,
`DISTINCTCOUNT counts unique values. COUNT and COUNTA count every non-blank row, and COUNTROWS counts every row.`,
[``,`COUNT counts all non-blank values, including repeats.`,`COUNTROWS counts sales rows, not customers.`,`COUNTA counts non-blank values including repeats.`],
`عدد العملاء المختلفين = DISTINCTCOUNT.`,['stat']),

Q('dax','single',2,'DIVIDE',
`You need a Margin % measure that returns blank instead of an error when Revenue is zero. Which expression is best?`,
[`DIVIDE([Profit], [Revenue])`,`[Profit] / [Revenue]`,`IFERROR([Profit] / [Revenue], 0)`,`DIVIDE([Revenue], [Profit])`],0,
`DIVIDE handles division by zero and returns blank (or an alternate result you provide). It's clearer and faster than wrapping division in IFERROR.`,
[``,`The / operator returns infinity or an error when dividing by zero.`,`IFERROR works but is slower and returns 0, which can show misleading values.`,`The operands are reversed.`],
`للقسمة الآمنة استخدم DIVIDE.`,['divide']),

Q('dax','single',2,'CALCULATE',
`Which measure returns sales for the Bikes category only, regardless of the category selected in a slicer?`,
[`CALCULATE([Sales], Product[Category] = "Bikes")`,`FILTER(Sales, RELATED(Product[Category]) = "Bikes")`,`[Sales] * (Product[Category] = "Bikes")`,`CALCULATE([Sales], KEEPFILTERS(Product[Category] = "Bikes"))`],0,
`A Boolean filter in CALCULATE replaces any existing filter on Product[Category] with Bikes, so the result is Bikes sales even when the slicer selects something else.`,
[``,`FILTER returns a table, not a number.`,`You can't reference a column like that in a measure without row context.`,`KEEPFILTERS intersects with the slicer, so selecting Helmets would return blank.`],
`CALCULATE مع فلتر بسيط يستبدل فلتر العمود نفسه، وKEEPFILTERS يجعله تقاطعًا.`,['calculate']),

Q('dax','single',2,'CALCULATE',
`You need a measure that shows total sales for all categories on every row of a table visual grouped by category, to calculate each category's share. Which expression returns the grand total?`,
[`CALCULATE([Sales], REMOVEFILTERS(Product[Category]))`,`CALCULATE([Sales], Product[Category])`,`SUM(Sales[Amount])`,`CALCULATE([Sales], VALUES(Product[Category]))`],0,
`REMOVEFILTERS (or ALL) removes the filter coming from the category row, so the measure returns the total across all categories. Divide [Sales] by it to get the share.`,
[``,`A column reference alone isn't a valid filter here.`,`SUM respects the category filter of each row.`,`VALUES keeps the current category filter.`],
`لإزالة فلتر عمود داخل CALCULATE استخدم REMOVEFILTERS أو ALL.`,['calculate']),

Q('dax','yesno',3,'CALCULATE',
`Consider this measure:<pre>Sales Red = CALCULATE ( [Sales], Product[Color] = "Red" )</pre>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`In a visual grouped by Product[Color], every row shows the sales of red products.`,`The measure still respects a slicer on Customer[Country].`,`Wrapping the filter in KEEPFILTERS would make non-red rows return blank.`],
[true,true,true],
`The Boolean filter overrides the Color filter from the row, so every color row shows red sales. Filters on other columns, such as Country, stay. KEEPFILTERS intersects the new filter with the existing one, so only the Red row keeps a value.`,
[`Yes. The Color filter from the row is replaced.`,`Yes. CALCULATE only replaces filters on the columns it filters.`,`Yes. The intersection of Blue and Red is empty.`],
`فلتر CALCULATE يستبدل فلتر نفس العمود فقط، وKEEPFILTERS يحوّله إلى تقاطع.`,['calculate']),

Q('dax','single',1,'Time intelligence',
`You need year-to-date sales that reset each January, using a marked Date table. Which measure is correct?`,
[`TOTALYTD([Sales], 'Date'[Date])`,`SUM(Sales[Amount])`,`CALCULATE([Sales], 'Date'[Year])`,`DATESYTD([Sales])`],0,
`TOTALYTD evaluates the measure from the start of the year up to the last date in the current filter context. It's shorthand for CALCULATE([Sales], DATESYTD('Date'[Date])).`,
[``,`A plain sum doesn't accumulate.`,`A column reference alone isn't a valid filter.`,`DATESYTD takes a date column and returns a table of dates, not a measure.`],
`المجموع منذ بداية السنة: TOTALYTD أو CALCULATE مع DATESYTD.`,['ti']),

Q('dax','single',2,'Time intelligence',
`Your fiscal year ends on 30 June. Which measure returns fiscal year-to-date sales?`,
[`TOTALYTD([Sales], 'Date'[Date], "06-30")`,`TOTALYTD([Sales], 'Date'[Date])`,`TOTALQTD([Sales], 'Date'[Date])`,`DATEADD('Date'[Date], -6, MONTH)`],0,
`TOTALYTD and DATESYTD accept a year-end date as text, such as "06-30", so the year-to-date resets on 1 July.`,
[``,`Without the year-end argument, the year resets on 1 January.`,`TOTALQTD is quarter to date.`,`DATEADD shifts dates and returns a table, not a measure.`],
`السنة المالية: مرر تاريخ نهاية السنة مثل "06-30" إلى TOTALYTD.`,['ti']),

Q('dax','single',2,'Time intelligence',
`You need sales for the same period last year to compare with current sales in any date grouping (month, quarter or year). Which measure should you use?`,
[`CALCULATE([Sales], SAMEPERIODLASTYEAR('Date'[Date]))`,`CALCULATE([Sales], PREVIOUSYEAR('Date'[Date]))`,`[Sales] - 365`,`CALCULATE([Sales], 'Date'[Year] = YEAR(TODAY()) - 1)`],0,
`SAMEPERIODLASTYEAR shifts the current set of dates back by one year, so it works at month, quarter or year level.`,
[``,`PREVIOUSYEAR returns the entire previous year, not the matching period.`,`Subtracting 365 from sales is meaningless.`,`That hard-codes last calendar year and ignores the visual's grouping.`],
`للمقارنة بنفس الفترة من السنة الماضية استخدم SAMEPERIODLASTYEAR.`,['ti']),

Q('dax','single',3,'Time intelligence',
`You need a year-over-year growth % measure that returns blank when there are no prior year sales. Which expression is best?`,
[`VAR PY = CALCULATE([Sales], SAMEPERIODLASTYEAR('Date'[Date])) RETURN DIVIDE([Sales] - PY, PY)`,`([Sales] - [Sales]) / [Sales]`,`DIVIDE([Sales], CALCULATE([Sales], SAMEPERIODLASTYEAR('Date'[Date])))`,`[Sales] / CALCULATE([Sales], PREVIOUSYEAR('Date'[Date])) - 1`],0,
`A variable stores the prior year value once. DIVIDE returns blank when the prior year is blank or zero, and the numerator is the change.`,
[``,`That always returns zero.`,`This is a ratio, not growth, and it's 100% when there's no change.`,`PREVIOUSYEAR returns the full year, and the / operator fails on zero.`],
`نسبة النمو: (الحالي - السابق) / السابق باستخدام DIVIDE ومتغير VAR.`,['ti','divide']),

Q('dax','single',2,'Time intelligence',
`You need a rolling 3-month sales measure that includes the current month. Which expression is correct?`,
[`CALCULATE([Sales], DATESINPERIOD('Date'[Date], MAX('Date'[Date]), -3, MONTH))`,`CALCULATE([Sales], DATEADD('Date'[Date], -3, MONTH))`,`CALCULATE([Sales], PREVIOUSMONTH('Date'[Date]))`,`TOTALMTD([Sales], 'Date'[Date]) * 3`],0,
`DATESINPERIOD returns the dates from the last visible date back three months, covering a rolling window.`,
[``,`DATEADD shifts the period by three months instead of widening it.`,`PREVIOUSMONTH returns only the previous month.`,`Multiplying month-to-date by 3 is an estimate, not a rolling total.`],
`المجموع المتحرك لآخر 3 أشهر: DATESINPERIOD بقيمة -3 MONTH.`,['ti']),

Q('dax','single',2,'Semi-additive',
`An Inventory table stores the stock quantity per product for each day. Stock should be summed across products but not across dates; each month should show the stock on the last day of the month. Which measure is correct?`,
[`CLOSINGBALANCEMONTH(SUM(Inventory[Qty]), 'Date'[Date])`,`SUM(Inventory[Qty])`,`AVERAGE(Inventory[Qty])`,`TOTALMTD(SUM(Inventory[Qty]), 'Date'[Date])`],0,
`Stock is semi-additive: it adds across products but not across time. CLOSINGBALANCEMONTH returns the value at the last date of the month.`,
[``,`SUM adds every day's stock, overstating the month.`,`An average isn't the closing balance.`,`TOTALMTD accumulates across days, which is wrong for balances.`],
`الأرصدة شبه تراكمية: استخدم CLOSINGBALANCEMONTH أو LASTDATE.`,['closing']),

Q('dax','single',3,'Semi-additive',
`Account balances are loaded only on days when they change. A month's closing balance must use the last date that has a value, not the last calendar day. Which expression fits best?`,
[`CALCULATE(SUM(Balance[Amount]), LASTNONBLANK('Date'[Date], CALCULATE(SUM(Balance[Amount]))))`,`CALCULATE(SUM(Balance[Amount]), LASTDATE('Date'[Date]))`,`SUM(Balance[Amount])`,`MAX(Balance[Amount])`],0,
`LASTNONBLANK finds the last date in the period where the expression isn't blank, so the balance comes from the latest day that has data.`,
[``,`LASTDATE uses the last calendar day, which may have no balance row.`,`SUM adds balances across days.`,`MAX returns the largest balance, not the latest.`],
`لو البيانات غير يومية استخدم LASTNONBLANK لآخر يوم فيه قيمة.`,['lastnb']),

Q('dax','single',1,'Quick measures',
`A new analyst needs a running total measure but isn't comfortable writing DAX. What should they use?`,
[`Quick measures, choosing the Running total calculation`,`Performance Analyzer`,`Column from examples`,`A what-if parameter`],0,
`Quick measures generate the DAX for common calculations such as running totals, year-to-date or percent of total from a dialog. The generated DAX can be reviewed and edited.`,
[``,`Performance Analyzer measures performance.`,`Column from examples is a Power Query feature.`,`What-if parameters create scenario inputs.`],
`Quick measures تكتب DAX جاهزًا لحسابات شائعة مثل Running total.`,['quickm']),

Q('dax','single',2,'Statistics',
`You need the middle value of order amounts, which is less affected by a few huge orders than the average. Which function should you use?`,
[`MEDIAN(Sales[Amount])`,`AVERAGE(Sales[Amount])`,`STDEV.P(Sales[Amount])`,`MAX(Sales[Amount])`],0,
`MEDIAN returns the middle value of the sorted numbers, so outliers affect it far less than the mean.`,
[``,`Averages are pulled up by outliers.`,`Standard deviation measures spread, not the center.`,`MAX returns the largest value.`],
`القيمة الوسطى الأقل تأثرًا بالقيم الشاذة = MEDIAN.`,['stat']),

Q('dax','multi',2,'Statistics',
`Which two DAX functions are statistical functions that measure the spread of values? Each correct answer presents a complete solution. Select TWO.`,
[`STDEV.P`,`VAR.S`,`MEDIAN`,`RANKX`,`DISTINCTCOUNT`],
[0,1],
`Standard deviation and variance describe how spread out values are around the mean. MEDIAN describes the center, RANKX ranks items and DISTINCTCOUNT counts unique values.`,
[`Correct.`,`Correct.`,`MEDIAN measures the center.`,`RANKX returns a rank.`,`DISTINCTCOUNT counts values.`],
`الانحراف المعياري والتباين يقيسان التشتت.`,['stat']),

Q('dax','single',2,'Calculation groups',
`You have 20 base measures and need YTD, PY and YoY % versions of each. You want to avoid creating 60 more measures. What should you create?`,
[`A calculation group with YTD, PY and YoY % calculation items that use SELECTEDMEASURE()`,`60 quick measures`,`A field parameter`,`A calculated column for each version`],0,
`Calculation items apply the same logic to whichever measure is in the visual through SELECTEDMEASURE(), so three items replace sixty measures.`,
[``,`That's the 60 measures you want to avoid.`,`Field parameters switch fields but don't apply time logic.`,`Calculated columns can't respond to filters like measures do.`],
`مجموعة حسابات Calculation group مع SELECTEDMEASURE تقلل عدد المقاييس المكررة.`,['calcgrp','selmeasure']),

Q('dax','yesno',3,'Calculation groups',
`You add your first calculation group in Model view of Power BI Desktop.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`Power BI requires the Discourage implicit measures property to be on.`,`Calculation items apply to columns dragged directly into a visual as implicit sums.`,`A calculation item can use a dynamic format string, for example to show YoY % as a percentage.`],
[true,false,true],
`Creating a calculation group turns on Discourage implicit measures because calculation items only apply to explicit measures. Items can have dynamic format strings.`,
[`Yes. You're prompted to turn it on.`,`No. Calculation items only work with explicit measures.`,`Yes. Turn on Dynamic format string on the item.`],
`Calculation groups تحتاج Discourage implicit measures، وتعمل على المقاييس الصريحة فقط، وتدعم dynamic format string.`,['calcgrp']),

Q('dax','single',2,'Calculated columns',
`In the Sales table you need a column with the product's category from the related Product table (many-to-one relationship). Which expression should you use in the calculated column?`,
[`RELATED(Product[Category])`,`RELATEDTABLE(Product)`,`LOOKUPVALUE(Sales[ProductID], Product[Category])`,`VALUES(Product[Category])`],0,
`RELATED follows a many-to-one relationship from the current row to the one side and returns a value.`,
[``,`RELATEDTABLE goes from the one side to the many side and returns a table.`,`The LOOKUPVALUE arguments are wrong and it's slower than RELATED when a relationship exists.`,`VALUES returns a table of values, not the row's value.`],
`لجلب قيمة من جدول الطرف الواحد إلى عمود محسوب استخدم RELATED.`,['calcopts']),

Q('dax','single',2,'Visual calculations',
`In a matrix of sales by month, you need a running total that only exists in this visual and doesn't add a measure to the shared model. What should you use?`,
[`A visual calculation: RUNNINGSUM([Sales])`,`A quick measure`,`A calculated column with RUNNINGSUM`,`A calculation group`],0,
`Visual calculations are stored on the visual, not in the model. RUNNINGSUM works only in visual calculations and follows the visual's axis.`,
[``,`A quick measure adds a measure to the model.`,`RUNNINGSUM can't be used in calculated columns.`,`Calculation groups are model objects.`],
`حساب خاص بـ visual واحد بدون تعديل النموذج: Visual calculation مثل RUNNINGSUM.`,['visualcalc']),

Q('dax','yesno',3,'Visual calculations',
`You're using visual calculations.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`MOVINGAVERAGE([Sales], 3) in a visual calculation averages the current row and the two previous rows by default.`,`Visual calculation results are included when a reader exports underlying data.`,`A visual calculation can be hidden in the visual while still being used by other visual calculations.`],
[true,false,true],
`MOVINGAVERAGE includes the current row by default. Exports of underlying data don't include visual calculation results. You can hide a helper visual calculation and reference it from others or from conditional formatting.`,
[`Yes. includeCurrent defaults to TRUE.`,`No. Underlying data exports don't include visual calculations.`,`Yes. Hidden visual calculations are common helpers.`],
`MOVINGAVERAGE يشمل الصف الحالي افتراضيًا، والتصدير لا يشمل visual calculations، ويمكن إخفاؤها واستخدامها.`,['visualcalc','export']),

Q('dax','single',3,'Variables',
`A measure calculates [Sales] three times inside an IF. It's slow and hard to read. What's the best improvement?`,
[`Store [Sales] in a VAR and reference the variable`,`Replace IF with SWITCH`,`Convert the measure to a calculated column`,`Wrap each [Sales] in CALCULATE`],0,
`Variables are evaluated once and reused, which improves both performance and readability.`,
[``,`SWITCH changes structure but still evaluates [Sales] several times.`,`A calculated column wouldn't respond to filters.`,`Extra CALCULATE calls add context transitions and don't reduce work.`],
`استخدم VAR لتخزين قيمة تتكرر في المقياس.`,['calculate']),

Q('dax','single',2,'Iterators',
`You need the rank of each product by sales, where 1 is the best seller, shown in a table visual by product. Which measure is correct?`,
[`RANKX(ALL(Product[ProductName]), [Sales])`,`RANKX(Product, Product[ProductName])`,`RANK.EQ([Sales], Sales[Amount])`,`TOPN(1, Product, [Sales])`],0,
`RANKX evaluates [Sales] for every product in the ALL table and ranks the current product's value among them, descending by default.`,
[``,`Ranking by the name column ranks alphabetically, not by sales.`,`RANK.EQ ranks a value in a column, not a measure across products.`,`TOPN returns a table, not a rank.`],
`لترتيب المنتجات حسب المبيعات: RANKX مع ALL.`,['stat']),

Q('dax','single',2,'Filter functions',
`A card must show sales for the product selected in a single-select slicer, and show "Select one product" otherwise. Which function detects a single selection?`,
[`HASONEVALUE(Product[ProductName])`,`ISBLANK(Product[ProductName])`,`ISFILTERED(Sales)`,`COUNTROWS(ALL(Product))`],0,
`HASONEVALUE returns TRUE when exactly one value is in the filter context for the column, so you can switch between the value and a prompt with IF.`,
[``,`ISBLANK checks a value, not the selection.`,`ISFILTERED only tells you a filter exists, not that one value remains.`,`ALL removes filters and counts every product.`],
`للتحقق من اختيار قيمة واحدة استخدم HASONEVALUE أو SELECTEDVALUE.`,['calculate']),

Q('dax','order',3,'Time intelligence',
`You need a YoY % measure that works with any date grouping. Which three measures should you create in sequence?`,
[`Sales = SUM(Sales[Amount])`,`Sales PY = CALCULATE([Sales], SAMEPERIODLASTYEAR('Date'[Date]))`,`Sales YoY % = DIVIDE([Sales] - [Sales PY], [Sales PY])`,`Sales PY = [Sales] - 365`,`Sales YoY % = [Sales] / [Sales]`],
[0,1,2],
`Build the base measure first, then the prior-year measure that reuses it, and finally the growth measure that divides the change by the prior year safely.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`Subtracting 365 from a sales total doesn't shift time.`,`That always returns 1.`],
`ابنِ المقاييس بالتدرج: الأساس ثم السنة السابقة ثم النسبة.`,['ti','divide'])
];
