// PL-300 bank, batch E: Optimize model performance, Create reports
const Q = require('./h.js');
module.exports = [
// ---------- perf ----------
Q('perf','single',1,'Performance Analyzer',
`A report page takes 12 seconds to load. You need to find which visual is slow and whether the time is spent on the DAX query or on rendering. What should you use?`,
[`Performance Analyzer in Power BI Desktop`,`Column profile in Power Query`,`Query dependencies view`,`The Selection pane`],0,
`Performance Analyzer records each visual's duration split into DAX query, Visual display and Other, so you can see which visual and which part is slow.`,
[``,`Column profile shows data statistics, not report performance.`,`Query dependencies show query lineage.`,`The Selection pane manages visibility and layering.`],
`لمعرفة الـ visual البطيء وسبب البطء استخدم Performance Analyzer.`,['perfan']),

Q('perf','single',2,'Performance Analyzer',
`Performance Analyzer shows that a table visual spends 9 seconds in DAX query. You want to test changes to its measure without clicking through the report. What should you do?`,
[`Copy the query from Performance Analyzer and run it in DAX query view`,`Export the visual to Excel`,`Change the page size`,`Turn on Auto date/time`],0,
`Performance Analyzer can copy the exact DAX query a visual sends. DAX query view in Desktop runs it, shows timings and lets you define and test alternative measures.`,
[``,`Exporting data doesn't help tune the query.`,`Page size doesn't change the query.`,`Auto date/time adds hidden tables and doesn't help.`],
`انسخ استعلام الـ visual من Performance Analyzer وجربه في DAX query view.`,['perfan','daxqv']),

Q('perf','yesno',2,'Performance Analyzer',
`You're reading Performance Analyzer results.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`A large Visual display time with a small DAX query time points to a visual that renders too many points or elements.`,`The Other category includes time a visual spends waiting for other visuals to finish.`,`Performance Analyzer results in Desktop measure how the report runs for every user in the service.`],
[true,true,false],
`Visual display is rendering time, often high for visuals with many data points or custom visuals. Other includes waiting and background work. Desktop timings depend on your machine and data, so they're indicators, not service measurements.`,
[`Yes.`,`Yes. Many visuals on a page make each one wait longer.`,`No. Service performance also depends on capacity, network and concurrent users.`],
`وقت Visual display الكبير يعني عرضًا ثقيلًا، وOther يشمل الانتظار، ونتائج Desktop مؤشرات فقط.`,['perfan']),

Q('perf','single',1,'Reduce data',
`Your Import model loads a Sales table with 10 years of history, but reports only cover the last 3 years. What's the simplest way to reduce model size and refresh time?`,
[`Filter the rows in Power Query to the last 3 years`,`Hide the old rows with a report-level filter`,`Create a measure that ignores old years`,`Change the table to Dual storage mode`],0,
`Filtering rows in Power Query stops unneeded rows from loading at all. Report filters and measures still leave every row in memory.`,
[``,`Filtered rows are still loaded.`,`A measure doesn't reduce the data loaded.`,`Dual keeps an imported copy anyway.`],
`أبسط تقليل للحجم: فلترة الصفوف غير المطلوبة في Power Query.`,['datared']),

Q('perf','multi',2,'Reduce data',
`Which two actions reduce the size of an Import semantic model? Each correct answer presents a complete solution. Select TWO.`,
[`Remove columns that no report or measure uses`,`Reduce the granularity of the fact table by grouping to daily totals when transaction detail isn't needed`,`Hide unused columns`,`Add more calculated columns`,`Turn on Auto date/time`],
[0,1],
`Removing columns and summarizing to a coarser grain both reduce the amount of data stored. Hiding columns doesn't remove them, and calculated columns and auto date tables add size.`,
[`Correct.`,`Correct.`,`Hidden columns are still stored.`,`Calculated columns add stored data.`,`Auto date/time adds hidden tables.`],
`حذف الأعمدة وتقليل مستوى التفصيل يصغّر النموذج، أما الإخفاء فلا.`,['datared']),

Q('perf','single',2,'Reduce data',
`A fact table has a DateTime column with seconds, making it the largest column in the model. Reports only need dates and hours. What should you do?`,
[`Split it into a Date column and an Hour column (or round it) in Power Query`,`Change it to Text`,`Hide the column`,`Create a calculated column that extracts the date`],0,
`High-cardinality columns compress poorly. Splitting a timestamp into date and a small time part greatly reduces the number of unique values and memory.`,
[``,`Text is still high cardinality and loses date features.`,`Hidden columns still take memory.`,`A calculated column adds data and keeps the original.`],
`قلل عدد القيم الفريدة: افصل التاريخ عن الوقت أو قرّب الوقت.`,['datared']),

Q('perf','single',2,'Relationships',
`A visual is slow. The model relates two large fact tables through a many-to-many relationship with bi-directional filtering. What change most likely improves performance?`,
[`Replace it with shared dimension tables in a star schema with single-direction relationships`,`Add more bi-directional relationships`,`Turn off query folding`,`Add a calculated column to each fact table`],0,
`Star schemas with single-direction one-to-many relationships are what the engine is optimized for. Fact-to-fact many-to-many relationships with bi-directional filters are expensive and ambiguous.`,
[``,`More bi-directional filters add cost.`,`Folding affects refresh, not this visual.`,`Calculated columns increase size and don't fix the relationship.`],
`علاقات many-to-many ثنائية الاتجاه بين جداول الحقائق بطيئة، استبدلها بـ star schema.`,['star','bidi']),

Q('perf','single',3,'Measures',
`A measure uses FILTER(Sales, Sales[Color] = "Red") inside CALCULATE and is slow on a 50 million row table. What's the better expression?`,
[`CALCULATE([Sales], Product[Color] = "Red") using the Product dimension column`,`CALCULATE([Sales], FILTER(ALL(Sales), Sales[Color] = "Red"))`,`SUMX(FILTER(Sales, Sales[Color] = "Red"), Sales[Amount]) * 2`,`A calculated column that multiplies Amount by 1`],0,
`Filtering a whole fact table with FILTER iterates every row. A simple column filter on a dimension column lets the engine filter efficiently and reuse the relationship.`,
[``,`FILTER(ALL(Sales)) iterates the full table and also removes other filters.`,`That still iterates the table and doubles the result.`,`That does nothing useful.`],
`تجنب FILTER على جدول حقائق كامل، واستخدم فلتر عمود بسيط على البعد.`,['calculate']),

Q('perf','single',1,'Visuals',
`A report page has 35 visuals and loads slowly. Most are small cards. What's the recommended design change?`,
[`Reduce the number of visuals, for example by combining cards into one multi-row card or table, or moving detail to other pages`,`Add more slicers`,`Use a larger page size`,`Turn on automatic page refresh`],0,
`Every visual sends its own query. Fewer, well-chosen visuals per page load faster and are easier to read.`,
[``,`More slicers add more queries.`,`Page size doesn't reduce the queries.`,`Automatic page refresh adds even more queries.`],
`كل visual يرسل استعلامًا، قلل عددها لتسريع الصفحة.`,['perfan']),

Q('perf','single',2,'DAX query view',
`What can you do in DAX query view in Power BI Desktop?`,
[`Write and run DAX queries with EVALUATE, and define measures in the query to test them before adding them to the model`,`Edit Power Query M steps`,`Change relationship cardinality`,`Configure row-level security membership in the service`],0,
`DAX query view runs DAX queries against the model, shows results and lets you DEFINE MEASURE to test logic. You can then update the model with the tested measure.`,
[``,`M steps are edited in Power Query Editor.`,`Relationships are edited in Model view.`,`RLS membership is managed in the service.`],
`DAX query view لتشغيل استعلامات EVALUATE وتجربة المقاييس.`,['daxqv']),

Q('perf','yesno',2,'Reduce data',
`You're optimizing an Import model.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`Columns with fewer distinct values compress better in memory.`,`Changing a numeric key column from Text to Whole Number can reduce memory.`,`Incremental refresh reduces the number of rows stored in the model.`],
[true,true,false],
`The VertiPaq engine compresses by distinct values, so low cardinality helps and integers store efficiently. Incremental refresh reduces the data refreshed each time, not the history kept in the model.`,
[`Yes.`,`Yes. Integer keys are usually smaller than text keys.`,`No. It refreshes only recent partitions but keeps the full history.`],
`القيم الفريدة الأقل تضغط أفضل، والأرقام أصغر من النصوص، وincremental refresh يسرّع التحديث ولا يقلل التاريخ المخزن.`,['datared','incr']),

Q('perf','single',2,'Reduce data',
`Your model has a Customer table with 3 million rows, but the Sales table only references 200,000 of those customers. Reports never show customers without sales. What's a good optimization?`,
[`Filter the Customer query to customers that appear in Sales (for example with an inner join or a list of keys)`,`Hide the Customer table`,`Mark Customer as a date table`,`Set Customer to DirectQuery`],0,
`Loading only dimension rows that the fact table uses reduces memory and speeds up filtering. An inner merge or a filter on a list of used keys does this in Power Query.`,
[``,`Hidden tables are still loaded.`,`Customer isn't a date table.`,`DirectQuery on a dimension usually slows visuals down.`],
`لا تحمّل صفوف أبعاد غير مستخدمة في جدول الحقائق.`,['datared']),

// ---------- reports ----------
Q('reports','single',1,'Choose a visual',
`You need to show how monthly revenue changed over the past 24 months. Which visual is most appropriate?`,
[`Line chart`,`Pie chart`,`Table`,`Card`],0,
`Line charts show trends over continuous time clearly.`,
[``,`Pie charts compare parts of a whole at one point in time.`,`Tables are for exact values, not trends.`,`Cards show a single number.`],
`للاتجاه عبر الزمن استخدم Line chart.`,['visuals']),

Q('reports','single',1,'Choose a visual',
`You need to show how a starting profit becomes a final profit through positive and negative contributions such as price, volume and costs. Which visual fits best?`,
[`Waterfall chart`,`Funnel`,`Scatter chart`,`Treemap`],0,
`Waterfall charts show a running total as values are added or subtracted, which suits bridge or variance analysis.`,
[``,`Funnels show stages of a process.`,`Scatter charts show relationships between two measures.`,`Treemaps show part-to-whole with rectangles.`],
`تحليل الفروقات والجسور: Waterfall chart.`,['visuals']),

Q('reports','single',2,'Choose a visual',
`You need to compare actual sales against a target for a single KPI, showing the value, the goal and the trend over time in one visual. Which visual should you use?`,
[`KPI visual`,`Gauge without a target`,`Stacked column chart`,`Slicer`],0,
`The KPI visual shows an indicator value, a target (goal) and a trend axis with color coding for whether the goal is met.`,
[``,`A gauge can show a target but not the trend over time.`,`Stacked columns don't highlight a single KPI against a goal.`,`Slicers filter data.`],
`KPI visual يعرض القيمة والهدف والاتجاه معًا.`,['visuals']),

Q('reports','single',1,'Themes',
`Your company wants every new report to use the brand colors and fonts without formatting each visual. What should you do?`,
[`Create and apply a report theme JSON file`,`Format each visual and copy the format with Format painter`,`Set colors with conditional formatting`,`Use a bookmark`],0,
`A theme JSON defines data colors, text styles and default visual formatting for the whole report. Applying it styles every visual at once.`,
[``,`Format painter works one visual at a time.`,`Conditional formatting depends on data values.`,`Bookmarks capture report states.`],
`لتوحيد ألوان وخطوط التقارير استخدم theme JSON.`,['themes']),

Q('reports','single',2,'Conditional formatting',
`In a table visual, the Margin % column must show a red background below 10%, yellow from 10% to 20%, and green above 20%. What should you configure?`,
[`Conditional formatting on the background color, formatted by Rules`,`A theme with three data colors`,`Three bookmarks`,`A gradient color scale with default settings`],0,
`Rules-based conditional formatting sets exact thresholds and colors. Gradients blend colors and don't give sharp bands.`,
[``,`Theme colors aren't tied to values.`,`Bookmarks don't color cells.`,`A default gradient blends colors instead of fixed bands.`],
`ألوان بحدود دقيقة: Conditional formatting بـ Rules.`,['condfmt']),

Q('reports','single',2,'Conditional formatting',
`A column chart must color each bar with a hex color stored in a measure, for example green when above target and red when below. What should you use?`,
[`Conditional formatting on the data colors with Format style: Field value, pointing to the color measure`,`Rules with 20 conditions`,`A theme file`,`A tooltip page`],0,
`Field value formatting reads a color (hex code or color name) from a measure or column, so the logic lives in DAX and is easy to maintain.`,
[``,`Many rules are hard to maintain and can't compare to a target measure easily.`,`Theme colors don't depend on values.`,`Tooltips don't color bars.`],
`لون يُحسب في DAX: Conditional formatting بخيار Field value.`,['condfmt']),

Q('reports','single',1,'Slicers',
`Users need to pick a date range with a start and end date on the report page. Which slicer style fits best?`,
[`A date slicer set to Between`,`A list slicer with every date`,`A dropdown slicer with single select`,`A relative date slicer set to Next 3 months`],0,
`A Between date slicer shows a range with start and end inputs and a timeline slider.`,
[``,`Listing every date is hard to use.`,`Single select allows only one date.`,`Relative date shows rolling periods, not a custom range.`],
`لاختيار فترة من-إلى استخدم date slicer بنمط Between.`,['slicers']),

Q('reports','single',2,'Filters',
`A filter must apply to every page of a report, but report readers must not be able to change it. What should you do?`,
[`Add it to Filters on all pages and lock it`,`Add a slicer to each page`,`Add it to Filters on this visual`,`Hide the Filters pane on one page only`],0,
`Report-level filters apply to all pages. Locking a filter keeps it visible but stops readers from changing it, and hiding it keeps it invisible.`,
[``,`Slicers can be changed by readers.`,`Visual-level filters affect one visual.`,`The filter still needs to be report level.`],
`فلتر على كل الصفحات ولا يتغير: Filters on all pages ثم Lock.`,['reportsettings']),

Q('reports','yesno',2,'Copilot',
`You plan to use Copilot in Power BI to create a report page and a narrative visual.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`The report must be in a workspace on a paid Fabric capacity or Power BI Premium (P1 or higher).`,`Copilot is supported on Fabric trial capacities.`,`To add a narrative visual with Copilot, you need edit access to the report or Build access to the semantic model.`],
[true,false,true],
`Copilot requires a paid Fabric capacity or Premium P1+, and trial SKUs aren't supported. Adding a narrative visual is an authoring action, so it needs edit access to the workspace or report or Build on the model.`,
[`Yes.`,`No. Only paid SKUs support Copilot.`,`Yes. Readers can still summarize in the Copilot pane.`],
`Copilot يحتاج Fabric capacity مدفوعة أو Premium، ولا يعمل على trial، وإضافة narrative visual تحتاج صلاحية تعديل.`,['copilotreq','copilotnarr']),

Q('reports','single',2,'Copilot',
`You want Copilot to propose an outline of report pages based on your semantic model before you build anything. Which Copilot capability should you use?`,
[`Suggest content for a new report page`,`Create a narrative visual`,`Write DAX queries`,`Add measure descriptions`],0,
`Suggest content evaluates the data and returns an outline of suggested pages you can choose to create.`,
[``,`A narrative summarizes existing visuals.`,`DAX queries return data, not a report outline.`,`Measure descriptions document the model.`],
`لاقتراح صفحات التقرير استخدم Suggest content في Copilot.`,['copilotov','copilotrep']),

Q('reports','single',2,'Copilot',
`A narrative visual created with Copilot summarizes the visuals on a page. After users change a slicer, the summary still shows the old numbers. What's expected behavior?`,
[`Users must refresh the narrative visual to regenerate the summary after filters change`,`The visual can't read slicers`,`The visual only summarizes the semantic model, not the page`,`Copilot narratives never update`],0,
`The narrative is generated from the visuals on the page. When the page is filtered or the data changes, users refresh the narrative to get an updated summary.`,
[``,`The summary reflects the page's filters after it's refreshed.`,`It summarizes what's on the report canvas.`,`It updates when refreshed.`],
`بعد تغيير الفلاتر يجب تحديث الـ narrative visual ليعكس الأرقام الجديدة.`,['copilotnarr']),

Q('reports','single',2,'Paginated reports',
`Finance needs a 40-page invoice listing that prints exactly, with a header on every page and every row shown, exported to PDF. What should you build?`,
[`A paginated report in Power BI Report Builder`,`A Power BI report with a table visual`,`A dashboard`,`A mobile layout`],0,
`Paginated reports are designed for pixel-perfect, printable output that spans pages and shows all rows, with repeated headers and exports to PDF.`,
[``,`Interactive reports scroll inside visuals and aren't designed for exact multi-page printing.`,`Dashboards are single-page tile canvases.`,`Mobile layouts optimize for phones.`],
`للطباعة الدقيقة متعددة الصفحات استخدم Paginated report.`,['paginated']),

Q('reports','multi',2,'Paginated reports',
`Which two scenarios are better served by a paginated report than an interactive Power BI report? Each correct answer presents a complete solution. Select TWO.`,
[`A regulatory statement that must print on fixed-size pages with exact layout`,`A detailed list of 50,000 transactions to export to Excel or PDF`,`An executive dashboard for exploring trends with drill-down`,`A mobile-first sales overview`,`A report that relies on cross-highlighting between charts`],
[0,1],
`Paginated reports excel at fixed layouts and long detailed lists for print or export. Exploration, cross-highlighting and mobile views are strengths of interactive reports.`,
[`Correct.`,`Correct.`,`Interactive reports suit exploration.`,`Mobile layouts are interactive report features.`,`Cross-highlighting is an interactive feature.`],
`الـ paginated للطباعة والقوائم الطويلة، والتفاعلية للاستكشاف.`,['paginated']),

Q('reports','single',2,'Page setup',
`You're building a report page to use as a tooltip for another page. What should you set on the tooltip page?`,
[`Page information: Allow use as tooltip, and set Canvas settings to the Tooltip size`,`Page visibility: Hidden only`,`A bookmark`,`Mobile layout`],0,
`A report page tooltip is a page with Allow use as tooltip turned on, usually sized as Tooltip. Visuals then point to it in their Tooltips settings.`,
[``,`Hiding the page doesn't make it a tooltip.`,`Bookmarks capture states.`,`Mobile layout is for phones.`],
`صفحة Tooltip: فعّل Allow use as tooltip واختر مقاس Tooltip.`,['tooltips']),

Q('reports','single',1,'Page setup',
`A report page should be taller than a screen so users can scroll down to more visuals. What should you change?`,
[`Canvas settings: set a custom page height`,`Page view: Fit to width only`,`The theme`,`The mobile layout`],0,
`Custom page sizes in Canvas settings allow longer pages. Fit to width controls how the page scales, not its height.`,
[``,`Fit to width scales the page but doesn't add space.`,`Themes don't set page size.`,`Mobile layout doesn't change the desktop page.`],
`لصفحة أطول غيّر ارتفاع الصفحة من Canvas settings.`,['reportsettings']),

Q('reports','single',2,'Visual calculations',
`In a matrix by Product and Month, you need each month's sales as a percentage of the product's total across months, without adding a model measure. What should you use?`,
[`A visual calculation using COLLAPSE, for example DIVIDE([Sales], COLLAPSE([Sales], COLUMNS))`,`A calculated column`,`A calculation group`,`A what-if parameter`],0,
`Visual calculations can reference parent levels in the visual matrix. COLLAPSE moves to the parent level (the product total across columns) so the share can be calculated on the visual only.`,
[``,`Calculated columns can't respond to the visual layout.`,`Calculation groups are model objects.`,`What-if parameters are scenario inputs.`],
`نسبة من إجمالي المستوى الأعلى داخل visual واحد: visual calculation مع COLLAPSE.`,['visualcalc']),

Q('reports','yesno',2,'Filters',
`You're reviewing filters in a report.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`A Top N filter on a visual can show the top 5 products by sales.`,`Filters on this page affect other pages.`,`A relative date filter can show the last 12 complete months.`],
[true,false,true],
`Top N is a visual or page filter type. Page filters stay on their page. Relative date filters support rolling periods such as last 12 calendar months.`,
[`Yes.`,`No. Use Filters on all pages for report scope.`,`Yes. Choose In the last 12 calendar months.`],
`Top N لأعلى القيم، وفلاتر الصفحة لا تؤثر على غيرها، وRelative date للفترات المتحركة.`,['slicers']),

Q('reports','single',2,'Field parameters',
`Users want to switch a chart's axis between Category, Region and Channel with a slicer, without separate charts. What should you create?`,
[`A field parameter with Category, Region and Channel`,`A what-if parameter`,`Three bookmarks`,`A calculation group`],0,
`Field parameters create a slicer that swaps the fields used in a visual, such as the axis or values.`,
[``,`What-if parameters create numeric inputs.`,`Bookmarks work but need three copies and buttons, which is harder to maintain.`,`Calculation groups change measures, not axis fields.`],
`لتبديل محور الرسم بـ slicer استخدم Field parameter.`,['fieldparams']),

Q('reports','single',1,'Formatting',
`A bar chart shows long product names that are cut off. What's the simplest formatting fix?`,
[`Use a bar chart (horizontal) and increase the Y-axis width or enable word wrap`,`Change to a pie chart`,`Remove the axis`,`Turn on data labels only`],0,
`Horizontal bar charts give category labels more room, and axis settings let you widen or wrap labels.`,
[``,`Pie charts with many categories are hard to read.`,`Removing the axis hides the names.`,`Data labels show values, not names.`],
`للأسماء الطويلة استخدم Bar chart أفقي ووسّع المحور.`,['visuals']),

Q('reports','single',2,'Choose a visual',
`You need to show the relationship between marketing spend and revenue for 200 stores and spot stores that don't follow the pattern. Which visual should you use?`,
[`Scatter chart`,`Donut chart`,`Ribbon chart`,`Card`],0,
`A scatter chart plots two measures against each other for each item, making correlation and outliers easy to see.`,
[``,`Donuts show part-to-whole.`,`Ribbon charts show rank changes over time.`,`Cards show one value.`],
`العلاقة بين مقياسين: Scatter chart.`,['visuals'])
];
