// PL-300 bank, batch F: Enhance reports for usability and storytelling, Identify patterns and trends
const Q = require('./h.js');
module.exports = [
Q('reports','single',2,'Report settings',
`Report readers should be able to export only the summarized data that a visual shows, never the underlying rows. What should you configure?`,
[`Report settings: Export data set to Allow end users to export only summarized data`,`Hide the columns in the model`,`A visual-level filter`,`Row-level security`],0,
`The Export data report setting controls whether readers can export summarized and underlying data, only summarized data, or nothing. Tenant settings can restrict it further.`,
[``,`Hidden columns can still be exported as underlying data in some cases.`,`Filters don't control export options.`,`RLS limits rows by user, not export type.`],
`للتحكم في التصدير استخدم إعداد Export data في Report settings.`,['reportsettings','export']),

Q('reports','single',2,'Automatic page refresh',
`A DirectQuery report on a production database must update its visuals every 5 minutes while the page is open. What should you configure?`,
[`Automatic page refresh on the page with a fixed interval of 5 minutes`,`Scheduled refresh every 5 minutes`,`A dashboard tile refresh`,`Incremental refresh`],0,
`Automatic page refresh re-queries DirectQuery sources at a fixed interval while the page is open. Scheduled refresh applies to imported data and can't run every 5 minutes.`,
[``,`Scheduled refresh is for Import and allows at most 8 or 48 refreshes per day.`,`Dashboard tile cache refresh doesn't update the report page.`,`Incremental refresh partitions imported data.`],
`تحديث صفحة DirectQuery كل عدة دقائق: Automatic page refresh.`,['apr']),

// ---------- usability ----------
Q('usability','single',1,'Bookmarks',
`You want a button that switches a page between a chart view and a table view. What should you use?`,
[`Two bookmarks that show and hide the visuals, and buttons that trigger them`,`Two report pages with drillthrough`,`A field parameter`,`Edit interactions`],0,
`Bookmarks capture the visibility state of visuals (set in the Selection pane). Buttons with a Bookmark action switch between them.`,
[``,`Drillthrough passes filters to a detail page.`,`Field parameters swap fields, not whole visuals.`,`Edit interactions control cross-filtering.`],
`للتبديل بين عرضين على نفس الصفحة: Bookmarks مع Selection pane وأزرار.`,['bookmarks']),

Q('usability','single',2,'Bookmarks',
`A bookmark should only change which visuals are visible, and must not reset the filters and slicer choices users made. What should you do?`,
[`Clear the Data option on the bookmark`,`Clear the Display option on the bookmark`,`Clear the Current page option on the bookmark`,`Select All visuals`],0,
`The Data option captures filters and slicers. Turning it off makes the bookmark apply only display properties such as visibility, so user filters stay.`,
[``,`Display controls visibility, which you need to keep.`,`Current page controls navigation to the page.`,`All visuals affects scope, not whether filters are captured.`],
`لإبقاء فلاتر المستخدم ألغِ خيار Data في الـ bookmark.`,['bookmarks']),

Q('usability','yesno',2,'Bookmarks',
`You're configuring bookmarks in Power BI Desktop.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`A bookmark can apply only to selected visuals.`,`A bookmark navigator visual creates buttons for a group of bookmarks automatically.`,`Readers in the service can create personal bookmarks without edit permissions.`],
[true,true,true],
`Bookmarks can target selected visuals, the bookmark navigator builds buttons from a bookmark group, and readers can save personal bookmarks in the service.`,
[`Yes. Use Selected visuals in the bookmark options.`,`Yes. Point the navigator at a bookmark group.`,`Yes. Personal bookmarks don't need edit rights.`],
`الـ bookmarks تدعم Selected visuals وBookmark navigator والـ personal bookmarks للقراء.`,['bookmarks']),

Q('usability','single',2,'Tooltips',
`When users hover over a region in a map, they should see a small chart of that region's monthly trend. What should you create?`,
[`A report page tooltip and assign it in the map's Tooltips settings`,`A drillthrough page`,`A bookmark`,`A second map`],0,
`Report page tooltips show a whole mini page on hover, filtered to the hovered data point.`,
[``,`Drillthrough requires a click and navigates away.`,`Bookmarks don't show on hover.`,`A second map doesn't show on hover.`],
`لعرض رسم صغير عند المرور: Report page tooltip.`,['tooltips']),

Q('usability','single',1,'Interactions',
`Selecting a bar in a column chart cross-highlights a donut chart, but you want the donut chart to be filtered instead. What should you change?`,
[`Edit interactions on the column chart and set the donut to Filter`,`Change the donut's theme`,`Add a slicer`,`Turn on drill down`],0,
`Edit interactions controls how a selected visual affects every other visual on the page: filter, highlight or none.`,
[``,`Themes don't change interactions.`,`A slicer adds another control but doesn't change the chart's behavior.`,`Drill down changes hierarchy levels.`],
`لتغيير Highlight إلى Filter استخدم Edit interactions.`,['interactions']),

Q('usability','single',2,'Interactions',
`A KPI card showing the company total must never change when users click other visuals on the page. What should you do?`,
[`In Edit interactions, set None on the card for each visual that could affect it`,`Lock the card in the Filters pane`,`Put the card on another page`,`Change the card to a table`],0,
`Setting the interaction to None stops cross-filtering from other visuals, so the card keeps showing the total. (Use REMOVEFILTERS in the measure if slicers must be ignored too.)`,
[``,`Filter pane locks apply to filters, not visual interactions.`,`Moving it hides it from the page's context.`,`Visual type doesn't stop interactions.`],
`لمنع تأثر الـ card بالنقر على غيره: Edit interactions ثم None.`,['interactions']),

Q('usability','single',1,'Navigation',
`You need a set of buttons across the top of every page that takes users to each page of the report and updates automatically when pages are added. What should you use?`,
[`A page navigator`,`Individual buttons with Page navigation actions`,`Bookmarks`,`Drillthrough`],0,
`The page navigator creates a button for each visible page and updates as pages are added, removed or renamed.`,
[``,`Individual buttons work but must be updated by hand.`,`Bookmarks capture states, not pages.`,`Drillthrough is for detail pages with filters.`],
`قائمة تنقل تلقائية بين الصفحات: Page navigator.`,['buttons']),

Q('usability','single',2,'Drillthrough',
`From a sales summary page, users should right-click a product and open a Product details page filtered to that product. What should you configure on the Product details page?`,
[`Add Product[ProductName] to the Drill through well of the details page`,`Add a slicer on ProductName`,`Create a bookmark per product`,`Turn on Personalize visuals`],0,
`Drillthrough pages have a Drill through field well. Any visual using that field offers a Drill through option that opens the page filtered to the selected value.`,
[``,`A slicer requires the user to reselect the product.`,`Bookmarks per product don't scale.`,`Personalization changes visuals, not navigation.`],
`صفحة تفاصيل مفلترة بالمنتج: أضف الحقل إلى Drill through.`,['drill']),

Q('usability','yesno',3,'Drillthrough',
`You're configuring drillthrough.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`With Keep all filters on, the target page also receives the filters from the source page's slicers.`,`Power BI adds a back button to a drillthrough page automatically.`,`Cross-report drillthrough can open a page in a different report in the same workspace.`],
[true,true,true],
`Keep all filters passes the whole filter context. A back button is added to new drillthrough pages. Cross-report drillthrough works across reports in the same workspace or app when enabled.`,
[`Yes.`,`Yes. It uses the Back action.`,`Yes. Turn on Cross-report on the target page and allow it in report settings.`],
`Keep all filters ينقل كل الفلاتر، وزر الرجوع يضاف تلقائيًا، ويمكن التنقل بين التقارير.`,['drill']),

Q('usability','single',2,'Drillthrough',
`A drillthrough button on the summary page should stay disabled until a user selects a product in a chart, and then open the details page. What should you configure?`,
[`A button with Action type Drill through and Destination set to the details page`,`A page navigator`,`A bookmark navigator`,`An image with a URL`],0,
`Drillthrough buttons are disabled until the selection meets the drill through fields of the destination page, then navigate with that filter.`,
[``,`Page navigators navigate without passing selection.`,`Bookmark navigators apply bookmarks.`,`Web URLs leave the report.`],
`زر Drill through يتفعّل بعد اختيار قيمة مناسبة.`,['buttons','drill']),

Q('usability','single',1,'Sync slicers',
`A Year slicer on the Overview page should also filter the Details and Trends pages, and appear only on Overview. What should you configure?`,
[`Sync slicers: sync the slicer to all three pages but make it visible only on Overview`,`Filters on this page on each page`,`Three separate slicers`,`Edit interactions`],0,
`The Sync slicers pane controls on which pages a slicer filters (sync) and where it's shown (visible), independently.`,
[``,`Page filters aren't linked to the slicer.`,`Separate slicers don't stay in sync.`,`Edit interactions apply within one page.`],
`Sync slicers يحدد أين يفلتر الـ slicer وأين يظهر.`,['slicers']),

Q('usability','single',2,'Selection pane',
`Two visuals overlap and the wrong one is on top, so users can't click the chart. What should you use?`,
[`The Selection pane to change the layer order`,`The Filters pane`,`Edit interactions`,`The Analytics pane`],0,
`The Selection pane lists visuals by layer. You can reorder them, group them, hide them and set tab order.`,
[``,`The Filters pane manages filters.`,`Interactions control cross-filtering.`,`The Analytics pane adds reference lines.`],
`ترتيب الطبقات والتجميع والإخفاء من Selection pane.`,['bookmarks']),

Q('usability','single',2,'Selection pane',
`Keyboard users navigate a report page with Tab, but focus jumps randomly between visuals and lands on decorative shapes. What should you do?`,
[`In the Selection pane, set the tab order and hide decorative objects from tab order`,`Change the theme`,`Add alt text to the shapes only`,`Move the page to a mobile layout`],0,
`Tab order in the Selection pane defines the keyboard sequence, and decorative items can be removed from the tab order so users skip them.`,
[``,`Themes don't control focus order.`,`Alt text helps screen readers but doesn't change tab order.`,`Mobile layout doesn't fix desktop keyboard navigation.`],
`ترتيب التنقل بلوحة المفاتيح من Tab order في Selection pane.`,['access']),

Q('usability','multi',2,'Accessibility',
`Which two practices make a report more accessible to users with visual impairments? Each correct answer presents a complete solution. Select TWO.`,
[`Add alt text to visuals`,`Use markers or patterns in addition to color to distinguish series`,`Use red and green as the only way to show good and bad`,`Put key information only in tooltips`,`Use very light gray text on white for a clean look`],
[0,1],
`Alt text is read by screen readers, and markers or labels mean color isn't the only way to tell series apart. Red and green alone fail for color vision deficiency, tooltips aren't reachable for everyone and low contrast text is hard to read.`,
[`Correct.`,`Correct.`,`Color alone excludes color-blind users.`,`Tooltips aren't accessible to every user.`,`Low contrast fails accessibility guidelines.`],
`للإتاحة: Alt text، وعدم الاعتماد على اللون وحده، وتباين كافٍ.`,['access']),

Q('usability','single',1,'Sorting',
`A bar chart of sales by region is sorted alphabetically. You need the largest region at the top. What should you do?`,
[`Use Sort axis on the visual and sort by the Sales measure, descending`,`Sort by column in the model`,`Rename the regions`,`Change the theme`],0,
`Visual sorting (More options > Sort axis) can sort by any field in the visual, including the measure, in ascending or descending order.`,
[``,`Sort by column defines a column's default order, not sorting by values.`,`Renaming doesn't reorder by value.`,`Themes don't sort.`],
`لترتيب الأعمدة حسب القيمة استخدم Sort axis على الـ visual.`,['sortby']),

Q('usability','single',2,'Mobile',
`Sales reps open reports on their phones in the Power BI app. The desktop layout is hard to read in portrait mode. What should you do?`,
[`Create a mobile layout for the key pages`,`Reduce the page size to phone dimensions`,`Publish a separate report for phones`,`Turn on automatic page refresh`],0,
`A mobile-optimized layout arranges selected visuals for portrait phones and appears automatically in the Power BI mobile apps. The desktop layout remains unchanged.`,
[``,`A small page would also shrink the desktop view.`,`A separate report doubles maintenance.`,`Page refresh doesn't affect layout.`],
`للهواتف أنشئ Mobile layout للصفحات المهمة.`,['mobile']),

Q('usability','yesno',2,'Mobile',
`You created mobile layouts in Power BI Desktop.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`The mobile layout is shown when the report is viewed in the Power BI mobile app in portrait orientation.`,`The mobile layout is shown in web browsers on a phone.`,`Changes you make to visual formatting in mobile layout don't change the desktop layout.`],
[true,false,true],
`Mobile-optimized views appear in the mobile apps in portrait. Browsers always show the standard layout. Mobile formatting changes are specific to the mobile layout.`,
[`Yes.`,`No. Browsers show the standard, non-optimized view.`,`Yes. Mobile format settings are independent.`],
`تخطيط الهاتف يظهر في تطبيق Power BI فقط، وتنسيقه مستقل عن تخطيط الكمبيوتر.`,['mobile']),

Q('usability','single',2,'Personalization',
`Readers want to change a chart's visual type and swap the measure in the Power BI service without edit rights, and save their version. What should you enable?`,
[`Personalize visuals in the report settings`,`Allow users to edit the report`,`Build permission on the semantic model`,`Automatic page refresh`],0,
`Personalize visuals lets readers change visual type, fields, legends and aggregations in reading view, and save changes as personal bookmarks.`,
[``,`Edit rights let them change the report for everyone.`,`Build permission lets them create new content, not personalize this report.`,`Page refresh is unrelated.`],
`لتخصيص القارئ للـ visuals بدون صلاحية تعديل: Personalize visuals.`,['personalize']),

Q('usability','single',2,'Export settings',
`A report on sensitive HR data must not allow readers to export any data from visuals, while still allowing them to view the report. What should you configure?`,
[`Report settings: Export data set to No export allowed`,`Remove the Export data button from the theme`,`Apply row-level security`,`Hide every column`],0,
`The report's Export data setting can block all exports. Admin tenant settings can override report settings, so check both.`,
[``,`Themes can't remove export.`,`RLS limits rows, not exports.`,`Hiding columns doesn't block export of what's shown.`],
`لمنع التصدير تمامًا: Export data = No export allowed.`,['reportsettings','export']),

Q('usability','single',3,'Automatic page refresh',
`You publish a DirectQuery report with automatic page refresh every 1 minute to a workspace on shared capacity (Pro). What happens in the service?`,
[`The refresh interval is limited to 30 minutes`,`It refreshes every minute`,`Automatic page refresh is removed from the report`,`It switches to Import mode`],0,
`Outside Premium or Fabric capacity, fixed-interval automatic page refresh is locked at a minimum of 30 minutes, and change detection isn't available.`,
[``,`Short intervals need a Premium or Fabric capacity that allows them.`,`The setting stays, with the shared-capacity limit.`,`Storage mode doesn't change.`],
`في Pro بدون Premium يكون أقل تحديث تلقائي للصفحة 30 دقيقة.`,['apr']),

Q('usability','order',2,'Tooltips',
`You need a custom tooltip showing a product's image and margin when users hover over bars in a sales chart. Which three actions should you perform in sequence?`,
[`Create a new page and turn on Allow use as tooltip in Page information`,`Add the image and margin visuals to the tooltip page, sized for a tooltip`,`On the sales chart, set Tooltips type to Report page and select the tooltip page`,`Add the tooltip page to the Drill through well`,`Create a bookmark for each product`],
[0,1,2],
`Create the tooltip page, design it, then point the visual's tooltip settings to it. Drill through wells and bookmarks aren't involved.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`Drillthrough is a different feature.`,`Bookmarks aren't needed for tooltips.`],
`الخطوات: صفحة tooltip ثم تصميمها ثم ربطها بالـ visual.`,['tooltips']),

// ---------- patterns ----------
Q('patterns','single',1,'Analyze',
`A line chart shows a sudden sales increase in March. You want Power BI to find which categories or regions explain the increase. What should you use?`,
[`Right-click the data point and select Analyze > Explain the increase`,`Performance Analyzer`,`Sync slicers`,`A what-if parameter`],0,
`The Analyze feature explores the data automatically and shows the factors that contributed most to an increase or decrease.`,
[``,`Performance Analyzer measures speed.`,`Sync slicers link slicers across pages.`,`What-if parameters create scenarios.`],
`لتفسير الزيادة أو النقصان استخدم Analyze > Explain the increase.`,['insights']),

Q('patterns','single',1,'Grouping and binning',
`You need to group customer ages into 10-year bands for a histogram. What's the fastest way?`,
[`Create a bin (New group > Bin) on the Age column with a bin size of 10`,`Write a nested IF measure`,`Create a hierarchy`,`Use a Top N filter`],0,
`Binning divides a numeric or date column into equal-size ranges, creating a new column you can use on an axis.`,
[``,`Measures can't be axes.`,`Hierarchies organize levels, not ranges.`,`Top N filters limit items.`],
`لتقسيم الأعمار إلى فئات متساوية استخدم Bin.`,['grouping']),

Q('patterns','single',2,'Grouping and binning',
`In a chart of sales by country, you want to combine five small countries into one Other group directly from the visual. What should you do?`,
[`Select the five countries, right-click and choose Group data`,`Create a calculated table`,`Unpivot the country column`,`Add a Top N filter`],0,
`Grouping creates a new group column where selected values are combined, and the rest can be kept or put into Other.`,
[``,`A calculated table isn't needed.`,`Unpivot reshapes columns.`,`Top N hides the countries instead of grouping them.`],
`لدمج قيم في مجموعة من الـ visual: Group data.`,['grouping']),

Q('patterns','single',2,'Clustering',
`You have a scatter chart of customers by frequency and spend, and you want Power BI to find natural segments automatically. What should you use?`,
[`Automatically find clusters on the scatter chart`,`Binning`,`A decomposition tree`,`A reference line`],0,
`Clustering groups similar data points in scatter charts (and tables) into segments and adds a cluster column you can reuse.`,
[``,`Bins split one column into equal ranges.`,`Decomposition trees break a measure down by dimensions.`,`Reference lines add a constant or statistic.`],
`لاكتشاف شرائح العملاء تلقائيًا: Automatically find clusters.`,['grouping']),

Q('patterns','single',2,'AI visuals',
`Marketing wants to know which factors most affect whether a customer gives a low satisfaction rating. Which visual should you use?`,
[`Key influencers`,`Decomposition tree`,`Q&A`,`Smart narrative`],0,
`The key influencers visual analyzes which factors drive a metric or outcome, such as a low rating, and ranks them.`,
[``,`Decomposition trees let users drill a measure down by dimensions, but don't rank drivers automatically.`,`Q&A answers natural language questions.`,`Smart narratives summarize visuals in text.`],
`لمعرفة العوامل المؤثرة في نتيجة: Key influencers.`,['keyinf']),

Q('patterns','single',2,'AI visuals',
`Managers want to break total sales down by region, then by product, then by channel, choosing the next level at each step themselves or letting AI pick the highest value. Which visual should you use?`,
[`Decomposition tree`,`Key influencers`,`Waterfall chart`,`Funnel`],0,
`The decomposition tree lets users drill a measure into any dimension in any order, with AI splits that pick the highest or lowest next value.`,
[``,`Key influencers ranks drivers of an outcome.`,`Waterfall shows adds and subtracts to a total.`,`Funnel shows process stages.`],
`تفكيك المقياس حسب أبعاد متعددة: Decomposition tree.`,['decomp']),

Q('patterns','single',2,'Anomaly detection',
`A line chart of daily website sessions over a year should automatically highlight unusual spikes and dips, with an explanation of possible reasons. What should you turn on?`,
[`Find anomalies in the Analytics pane of the line chart`,`Forecast`,`Error bars`,`Constant line`],0,
`Anomaly detection on line charts with a date axis flags values outside an expected range and can explain them using fields you choose.`,
[``,`Forecast projects future values.`,`Error bars show uncertainty ranges from measures.`,`Constant lines show fixed values.`],
`لإبراز القيم الشاذة في line chart: Find anomalies.`,['anomaly']),

Q('patterns','yesno',2,'Analytics pane',
`You're using the Analytics pane.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`You can add an average line to a column chart.`,`Forecasting is available on a line chart with a continuous date axis.`,`Forecasting is available on a pie chart.`],
[true,true,false],
`Reference lines such as average, median and constant lines are available on many charts. Forecasting needs a line chart with a continuous time axis. Pie charts don't support the Analytics pane features.`,
[`Yes.`,`Yes. The axis must be continuous, not categorical.`,`No.`],
`خط المتوسط متاح لكثير من الرسوم، والتنبؤ يحتاج line chart بمحور زمني مستمر.`,['analytics']),

Q('patterns','single',2,'Analytics pane',
`A line chart shows monthly sales with a measure for the lower and upper estimate range. You want to show that range around the line. What should you add?`,
[`Error bars using the lower and upper bound measures`,`A median line`,`A trend line`,`A Top N filter`],0,
`Error bars in the Analytics pane use measures for upper and lower bounds to draw ranges around each data point.`,
[``,`A median line is a single reference value.`,`A trend line shows direction, not a range.`,`Top N filters items.`],
`لإظهار نطاق حول الخط: Error bars بقيم الحد الأعلى والأدنى.`,['analytics']),

Q('patterns','single',1,'Q&A',
`Business users want to type questions like "total sales by region last year" and get a chart. Which visual should you add?`,
[`Q&A visual`,`Smart narrative`,`Key influencers`,`Paginated report visual`],0,
`The Q&A visual accepts natural language questions and returns the best-matching visual, which you can convert to a standard visual.`,
[``,`Smart narrative summarizes existing visuals.`,`Key influencers analyzes drivers.`,`Paginated report visuals embed a paginated report.`],
`للأسئلة باللغة الطبيعية: Q&A visual.`,['qa']),

Q('patterns','single',2,'Copilot',
`A new analyst wants a quick overview of what tables, measures and topics a semantic model covers before building a report. Which Copilot capability helps most?`,
[`Ask Copilot to summarize the underlying semantic model`,`Create a narrative visual`,`Add measure descriptions`,`Suggest content for a new page`],0,
`Copilot can summarize a semantic model in the Copilot pane, describing its data and important insights so the analyst understands it faster.`,
[``,`Narratives summarize visuals on a page.`,`Descriptions document measures, they don't summarize the model.`,`Suggest content proposes pages.`],
`لفهم الـ semantic model بسرعة اطلب من Copilot تلخيصه.`,['copilotov']),

Q('patterns','multi',3,'Outliers',
`You need to spot stores whose sales are unusually high or low compared with others. Which two approaches help? Each correct answer presents a complete solution. Select TWO.`,
[`A scatter chart of sales against store size, looking for points far from the cluster`,`A box-and-whisker style comparison using percentile or standard deviation measures with conditional formatting`,`A pie chart of sales by store`,`A card with total sales`,`Sorting stores alphabetically`],
[0,1],
`Scatter charts reveal points far from the pattern, and measures based on percentiles or standard deviation can flag outliers with conditional formatting. Pies, totals and alphabetical sorting hide outliers.`,
[`Correct.`,`Correct.`,`Pies make comparisons between many stores hard.`,`A total hides the distribution.`,`Alphabetical order doesn't reveal outliers.`],
`لاكتشاف القيم الشاذة: Scatter chart أو مقاييس إحصائية مع تنسيق شرطي.`,['stat','visuals'])
];
