// PL-300 bank, batch G: Create and manage workspaces and assets, Secure and govern Power BI items
const Q = require('./h.js');
module.exports = [
// ---------- workspace ----------
Q('workspace','single',1,'Workspaces',
`Your team of five analysts needs a shared place to publish and co-edit semantic models and reports. Where should they publish?`,
[`A shared workspace with each analyst assigned a role`,`Each analyst's My workspace`,`A dashboard`,`An app`],0,
`Workspaces are the collaboration space for creators. My workspace is personal, and apps are for distributing content to consumers.`,
[``,`My workspace can't be shared for co-editing.`,`Dashboards are items, not publishing locations.`,`Apps distribute content read-only.`],
`للتعاون بين المطورين استخدم workspace مشتركة بأدوار.`,['createws','roles']),

Q('workspace','single',2,'Workspace roles',
`A user must publish and update reports in a workspace, but must not add people to the workspace or publish the workspace app. Which role should you assign?`,
[`Contributor`,`Member`,`Admin`,`Viewer`],0,
`Contributors can create, edit and delete content. Adding users and publishing the app requires Member or Admin.`,
[``,`Members can add users and publish the app.`,`Admins can do everything, including deleting the workspace.`,`Viewers can only view.`],
`نشر وتعديل المحتوى بدون إدارة الأعضاء أو التطبيق = Contributor.`,['roles']),

Q('workspace','yesno',2,'Workspace roles',
`You're assigning workspace roles.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`A Member can add other users as Members, Contributors or Viewers.`,`A Contributor can update the workspace app if the workspace Admin allows it.`,`A Viewer can download the .pbix file of a report.`],
[true,true,false],
`Members add users with the same or lower permissions. Admins can let Contributors update the app. Downloading .pbix files needs Contributor or higher.`,
[`Yes.`,`Yes. It's the Allow contributors to update the app setting.`,`No. Viewers can't download .pbix files.`],
`Member يضيف أعضاء بصلاحيات مساوية أو أقل، وContributor يحدّث التطبيق إذا سُمح له، وViewer لا ينزّل pbix.`,['roles']),

Q('workspace','single',1,'Apps',
`You need to distribute 6 reports and 2 dashboards to 800 sales employees in a consistent, read-only package with navigation. What should you use?`,
[`Publish a workspace app`,`Share each report individually`,`Add all 800 users as workspace Viewers`,`Email PDF exports`],0,
`Apps package content from a workspace with navigation and audiences, and they're the recommended way to distribute to large groups of consumers.`,
[``,`Sharing items one by one is hard to manage at scale.`,`Viewers see all workspace content, including work in progress.`,`PDFs are static and lose interactivity.`],
`لتوزيع محتوى على جمهور كبير: Workspace app.`,['apps']),

Q('workspace','single',2,'Apps',
`Managers should see all eight reports in the app, while the wider sales team sees only three. You want to maintain a single app. What should you configure?`,
[`Two audiences in the app, each with its own content and groups`,`Two workspaces`,`Row-level security`,`Two separate apps from the same workspace`],0,
`App audiences let one app show different content to different groups.`,
[``,`Two workspaces duplicate content.`,`RLS filters rows, not which reports appear.`,`A workspace can publish only one app.`],
`لإظهار محتوى مختلف لمجموعات مختلفة داخل تطبيق واحد: Audiences.`,['apps']),

Q('workspace','single',2,'Apps',
`You changed a report in the workspace, but app users still see the old version. What should you do?`,
[`Update the app`,`Refresh the semantic model`,`Clear the browser cache for all users`,`Republish the .pbix to My workspace`],0,
`Apps show the last published version of the content. After editing, select Update app so consumers get the changes.`,
[``,`Data refresh doesn't publish report design changes to the app.`,`The app itself hasn't been updated.`,`My workspace isn't the app's source.`],
`بعد تعديل التقرير يجب Update app حتى يراه المستخدمون.`,['apps']),

Q('workspace','single',1,'Publishing',
`You finished a report in Power BI Desktop. How do you get it to the team workspace?`,
[`Select Publish and choose the workspace`,`Save the .pbix to OneDrive only`,`Email the .pbix file`,`Export the report to PDF`],0,
`Publishing uploads the semantic model and report to the selected workspace.`,
[``,`Saving to OneDrive doesn't publish it (unless you import it from the service).`,`Emailing files breaks governance.`,`PDF is static.`],
`النشر من Desktop: Publish ثم اختر الـ workspace.`,['publish']),

Q('workspace','single',2,'Dashboards',
`Executives want a single page that combines key visuals from three different reports and lets them set alerts on KPI values. What should you create?`,
[`A dashboard with pinned tiles from the three reports`,`A new report page with copies of the visuals`,`A paginated report`,`An app audience`],0,
`Dashboards are single-page canvases in the service that can hold tiles pinned from several reports. Data alerts are set on dashboard tiles.`,
[``,`Copying visuals across reports requires combining models.`,`Paginated reports are for print layouts.`,`Audiences control app content visibility.`],
`لجمع visuals من عدة تقارير مع تنبيهات: Dashboard.`,['dash']),

Q('workspace','single',2,'Alerts',
`A manager wants an email when daily revenue drops below 50,000. On which item can a data alert be set?`,
[`A card, KPI or gauge tile on a dashboard`,`A line chart on a report page`,`A table visual in Power BI Desktop`,`A paginated report`],0,
`Data alerts are set in the service on dashboard tiles of type card, KPI and gauge.`,
[``,`Report visuals don't support data alerts.`,`Alerts aren't available in Desktop.`,`Paginated reports use subscriptions, not data alerts.`],
`التنبيهات تُضبط على tiles من نوع card أو KPI أو gauge في Dashboard.`,['alerts']),

Q('workspace','single',1,'Subscriptions',
`A regional manager wants a snapshot of a report page in their inbox every Monday at 8 AM. What should you set up?`,
[`An email subscription to the report page`,`A data alert`,`Automatic page refresh`,`A bookmark`],0,
`Subscriptions email a snapshot and link on a schedule.`,
[``,`Alerts trigger on thresholds, not schedules.`,`Page refresh updates visuals on screen.`,`Bookmarks don't send email.`],
`لإرسال التقرير بالبريد دوريًا: Subscription.`,['subs']),

Q('workspace','single',2,'Distribution',
`You need to share one report with three colleagues quickly. They have Pro licenses and aren't in the workspace. They must not be able to reshare it. What should you do?`,
[`Share the report with the three users and clear Allow recipients to share this report`,`Add them as workspace Members`,`Publish to web`,`Create an app for three users`],0,
`Direct sharing is quick for a few people, and you control resharing and build permissions in the share dialog.`,
[``,`Members get broad rights over every item.`,`Publish to web makes the report public on the internet.`,`An app works but is heavier than needed.`],
`مشاركة سريعة مع عدد قليل: Share مع إلغاء إعادة المشاركة.`,['share']),

Q('workspace','single',3,'Distribution',
`A marketing team wants to embed a report on the company's public website so anyone can see it without signing in. The data isn't confidential. Which option does this, and what's the main risk?`,
[`Publish to web; anyone with the link can see the data, with no security`,`Secure embed; it requires sign-in`,`An app; it's public by default`,`Share with the entire organization`],0,
`Publish to web creates a public embed code with no authentication, so it must only be used for public data and may be disabled by admins.`,
[``,`Secure embed requires sign-in.`,`Apps require sign-in and permissions.`,`Organization sharing still needs sign-in.`],
`Publish to web للمحتوى العام فقط لأنه بدون أي حماية.`,['share']),

Q('workspace','single',2,'Endorsement',
`Your Center of Excellence has verified that the Finance semantic model meets company standards. Only authorized reviewers can apply this badge. Which endorsement should be applied?`,
[`Certified`,`Promoted`,`Featured`,`Sensitivity label`],0,
`Certification is applied by reviewers authorized by the admin and signals the content meets organizational quality standards. Promotion can be applied by anyone with write permission.`,
[``,`Promotion doesn't require authorized reviewers.`,`Featured puts content on Home, it isn't endorsement.`,`Labels classify sensitivity, not quality.`],
`اعتماد رسمي من مراجعين مخولين = Certified.`,['endorse']),

Q('workspace','yesno',2,'Endorsement',
`You're using endorsement in Power BI.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`Any user with write permission on the workspace can promote a semantic model.`,`Dashboards can be certified.`,`Endorsed semantic models appear higher in lists when users choose a model to build on.`],
[true,false,true],
`Promotion is open to content owners and workspace writers. Dashboards can't be promoted or certified. Endorsed items are highlighted and prioritized in lists.`,
[`Yes.`,`No. Endorsement supports semantic models, reports, apps and dataflows, not dashboards.`,`Yes.`],
`الـ Promote لأي شخص لديه write، والـ dashboards لا تُعتمد، والمحتوى المعتمد يظهر أولًا.`,['endorse']),

Q('workspace','single',2,'Gateways',
`A semantic model uses an Excel file on a network file share (\\\\fs01\\finance\\budget.xlsx). Scheduled refresh fails in the service. What's missing?`,
[`An on-premises data gateway with a data source for the file share`,`A Premium capacity`,`A sensitivity label`,`Row-level security`],0,
`Files on a local network share are on-premises sources, so the service needs an on-premises data gateway to reach them.`,
[``,`Capacity type doesn't give network access.`,`Labels don't affect connectivity.`,`RLS doesn't affect refresh.`],
`الملفات على مشاركة شبكة داخلية تحتاج gateway للتحديث.`,['gw']),

Q('workspace','single',2,'Scheduled refresh',
`A semantic model in a Pro workspace needs to refresh every hour during working hours (10 times a day). What should you do?`,
[`Move the workspace to Premium Per User or a Fabric capacity, which allows up to 48 scheduled refreshes per day`,`Configure 10 time slots in the Pro workspace`,`Turn on automatic page refresh`,`Use incremental refresh`],0,
`Shared (Pro) capacity allows up to 8 scheduled refreshes per day. PPU, Premium and Fabric capacities allow up to 48.`,
[``,`Pro workspaces are limited to 8 scheduled refreshes.`,`Page refresh applies to DirectQuery pages, not Import refresh.`,`Incremental refresh speeds up refreshes but doesn't raise the limit.`],
`Pro يسمح بـ 8 تحديثات يوميًا، وPPU أو Fabric حتى 48.`,['sched']),

Q('workspace','yesno',2,'Scheduled refresh',
`You manage scheduled refresh for a semantic model.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`After four consecutive failures, Power BI turns off the refresh schedule.`,`If nobody views reports on the model for two months, scheduled refresh is paused.`,`A manual Refresh now counts toward the 8 scheduled refreshes per day on Pro.`],
[true,true,false],
`Four consecutive failures disable the schedule, and two months of inactivity pause it. Manual Refresh now in the UI isn't counted in the eight scheduled refreshes.`,
[`Yes. Fix the issue and turn the schedule back on.`,`Yes. Viewing a report resumes it.`,`No. UI-triggered on-demand refreshes aren't included in the limit.`],
`4 إخفاقات متتالية توقف الجدولة، وشهران بلا مشاهدة يوقفانها مؤقتًا، والتحديث اليدوي لا يُحسب.`,['sched','refresh']),

Q('workspace','order',2,'Scheduled refresh',
`A new Import semantic model uses an on-premises SQL Server. Which three actions should you perform in sequence to get a daily refresh working?`,
[`Install and register a standard on-premises data gateway that can reach the server`,`Add a connection for the SQL Server on the gateway and map the semantic model to it`,`Turn on Configure a refresh schedule in the semantic model settings and set the time`,`Set up a data alert on a dashboard tile`,`Create a personal bookmark`],
[0,1,2],
`Install the gateway, connect the model to the gateway data source (with credentials), then set the schedule.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`Alerts don't refresh data.`,`Bookmarks don't refresh data.`],
`الخطوات: gateway ثم connection للمصدر ثم جدولة التحديث.`,['gw','sched']),

Q('workspace','single',2,'Workspaces',
`A workspace must be assigned to a Fabric capacity so that Copilot and larger models are available. Where is this set?`,
[`Workspace settings > License info (license mode)`,`Report settings`,`The semantic model's Security page`,`Power BI Desktop options`],0,
`The workspace license mode (Pro, PPU, Premium or Fabric capacity) is set in the workspace settings by a workspace admin with the right capacity permissions.`,
[``,`Report settings affect one report.`,`Security manages RLS membership.`,`Desktop options don't change workspace capacity.`],
`ربط الـ workspace بـ capacity من إعدادات الـ workspace > License info.`,['createws']),

// ---------- security ----------
Q('security','single',1,'RLS',
`Sales managers must see only their own region's data in a report. What should you implement?`,
[`Row-level security roles with a filter on Region`,`A page-level filter`,`Hiding the Region column`,`A separate report per region`],0,
`RLS applies filters to the semantic model based on role membership, so every report on the model respects them.`,
[``,`Readers can change or see around report filters, and they aren't security.`,`Hiding columns doesn't restrict rows.`,`Separate reports multiply maintenance and don't protect the model.`],
`لتقييد الصفوف حسب المستخدم: Row-level security.`,['rls']),

Q('security','single',2,'RLS',
`Each salesperson should see only the customers assigned to them. A table maps each salesperson's email to their customers. Which DAX filter should you use in one RLS role on the mapping table?`,
[`[Email] = USERPRINCIPALNAME()`,`[Email] = "anna@contoso.com"`,`[Email] = USERNAME() || TRUE()`,`[Email] = SELECTEDVALUE([Email])`],0,
`Dynamic RLS compares a column to the signed-in user's UPN, so one role works for everyone.`,
[``,`Hard-coding needs one role per person.`,`OR TRUE() returns every row.`,`SELECTEDVALUE depends on report filters, not the user.`],
`RLS ديناميكي بدور واحد: USERPRINCIPALNAME().`,['rls','rlsg']),

Q('security','yesno',2,'RLS',
`RLS is configured on a semantic model in a workspace.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`RLS applies to users with the Viewer role in the workspace.`,`RLS applies to workspace Contributors.`,`RLS still applies to a Viewer who has Build permission and uses Analyze in Excel.`],
[true,false,true],
`RLS restricts users who only have read access, such as Viewers and app users. Admins, Members and Contributors can edit the model, so RLS doesn't restrict them. Build permission doesn't bypass RLS.`,
[`Yes.`,`No. Contributors, Members and Admins aren't restricted by RLS.`,`Yes. Build doesn't remove RLS.`],
`RLS يطبق على Viewer فقط، ولا يطبق على Contributor وما فوق، ويبقى مع Build.`,['rls']),

Q('security','single',2,'RLS',
`You created RLS roles in Power BI Desktop and published the model. Where do you assign users and groups to the roles?`,
[`In the Power BI service, on the semantic model's Security page`,`In Power BI Desktop, in Manage roles`,`In the workspace access list`,`In the report's Filters pane`],0,
`Role definitions (DAX filters) are authored in Desktop or web modeling, but membership is managed in the service on the semantic model's Security page.`,
[``,`Desktop defines roles and lets you test with View as, but doesn't assign members.`,`Workspace access sets workspace roles, not RLS roles.`,`Filters aren't security.`],
`تعريف الأدوار في Desktop، وإضافة الأعضاء في الخدمة من Security.`,['rls']),

Q('security','single',2,'RLS',
`You want to test an RLS role before publishing, to see the report as a member of the West role would. What should you use in Power BI Desktop?`,
[`Modeling > View as, then select the West role`,`Performance Analyzer`,`The Selection pane`,`DAX query view without roles`],0,
`View as lets you preview the report under one or more roles (and optionally another user), so you can check the filters.`,
[``,`Performance Analyzer measures speed.`,`Selection pane manages visuals.`,`DAX query view runs queries without applying a role unless configured.`],
`لاختبار الدور قبل النشر: View as في Desktop، وTest as role في الخدمة.`,['rls']),

Q('security','multi',2,'RLS',
`Which two types of groups can you add as members of an RLS role in the Power BI service? Each correct answer presents a complete solution. Select TWO.`,
[`Microsoft Entra security groups`,`Mail-enabled security groups or distribution groups`,`Microsoft 365 groups`,`Groups created inside Power BI`,`Workspace roles`],
[0,1],
`RLS membership supports security groups, mail-enabled groups and distribution groups. Microsoft 365 groups aren't supported, and Power BI has no groups of its own.`,
[`Correct.`,`Correct.`,`Microsoft 365 groups can't be added to RLS roles.`,`Power BI doesn't create groups.`,`Workspace roles aren't groups you can add.`],
`عضوية RLS تقبل security groups والـ mail-enabled/distribution groups وليس Microsoft 365 groups.`,['rls']),

Q('security','single',3,'RLS',
`An RLS role filters the Region dimension. Sales rows for that region are correctly filtered, but a Targets table related to Region isn't filtered. Targets has a many-to-one relationship to Region with single direction from Region. What's the most likely cause?`,
[`The relationship to Targets is inactive`,`RLS only filters fact tables`,`RLS requires bi-directional relationships to reach any table`,`The Region table must be hidden`],0,
`RLS filters propagate only through active relationships. If the Targets relationship is inactive, the filter doesn't reach it.`,
[``,`RLS filters the table it's defined on and propagates from there.`,`Single-direction relationships from the dimension already carry the filter.`,`Hiding tables doesn't affect RLS.`],
`فلاتر RLS تنتقل فقط عبر العلاقات النشطة.`,['rlsg']),

Q('security','single',1,'Item access',
`A colleague needs to build their own reports on your published semantic model, but shouldn't get a workspace role. What permission should you grant on the semantic model?`,
[`Build`,`Read only`,`Reshare only`,`Write`],0,
`Build permission lets users create new reports and composite models on the semantic model, use Analyze in Excel and query it, without a workspace role.`,
[``,`Read lets them view reports but not build new ones.`,`Reshare lets them share, not build.`,`Write lets them edit the model, more than needed.`],
`لبناء تقارير على الـ semantic model بدون دور في الـ workspace: Build.`,['build']),

Q('security','yesno',2,'Item access',
`You share a report directly with a user.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`The user gets read access to the underlying semantic model through the report.`,`Without RLS, the user can see all data in the model through the report, not only the data in visible visuals.`,`Clearing Allow recipients to build content with the data associated with this report prevents them from getting Build permission.`],
[true,true,true],
`Sharing a report grants read access to its model. Without RLS or OLS, data access isn't limited to what visuals show. The share dialog controls reshare and build permissions.`,
[`Yes.`,`Yes. Use RLS or OLS to restrict data.`,`Yes.`],
`مشاركة التقرير تمنح قراءة الـ model، وبدون RLS تُتاح كل البيانات، ويمكن منع Build من نافذة المشاركة.`,['share']),

Q('security','single',2,'Object-level security',
`HR analysts can see a Salary column, but other report users must not even know it exists, and visuals using it should fail for them. What should you implement?`,
[`Object-level security (OLS) on the Salary column for a role`,`Row-level security`,`Hide the Salary column`,`A sensitivity label`],0,
`OLS secures tables or columns so that users in the role can't query or see them.`,
[``,`RLS filters rows, not columns.`,`Hidden columns can still be queried.`,`Labels classify content but don't hide columns.`],
`لإخفاء عمود أمنيًا عن مستخدمين: Object-level security.`,['ols']),

Q('security','single',1,'Sensitivity labels',
`A report contains confidential financial data. When users export it to Excel or PDF, the files must stay protected and marked Confidential. What should you apply?`,
[`A Microsoft Purview sensitivity label on the report or semantic model`,`Row-level security`,`A theme with a red banner`,`Certified endorsement`],0,
`Sensitivity labels classify content and, when exported to supported files such as Excel, PowerPoint and PDF, the label and its protection travel with the file.`,
[``,`RLS filters rows but doesn't protect exported files.`,`A theme isn't protection.`,`Certification is about quality.`],
`لحماية الملفات المصدّرة: Sensitivity label من Purview.`,['labels']),

Q('security','yesno',2,'Sensitivity labels',
`Your tenant uses sensitivity labels in Power BI.<br>For each of the following statements, select Yes if the statement is true. Otherwise, select No.`,
[`A new report created in the service on a labeled semantic model inherits the model's label.`,`You can apply a sensitivity label in Power BI Desktop.`,`Exporting data to a .csv file keeps the sensitivity label.`],
[true,true,false],
`New content inherits the parent's label, and Desktop supports labeling .pbix files. CSV exports don't support sensitivity labels.`,
[`Yes.`,`Yes. The label is shown in the status bar and kept in the .pbix.`,`No. Only file types that support labels, such as Excel, keep them.`],
`التقارير الجديدة ترث التصنيف، ويمكن التصنيف في Desktop، وملفات CSV لا تحمل التصنيف.`,['labels','export']),

Q('security','single',2,'Workspace roles',
`To follow the principle of least privilege, business users who only read reports should get which access?`,
[`The app audience or the Viewer role`,`Member role`,`Contributor role`,`Admin role`],0,
`Consumers only need read access. Apps or the Viewer role give that, and RLS applies to them.`,
[``,`Members can manage content and users.`,`Contributors can change content.`,`Admins control everything.`],
`القارئ يأخذ Viewer أو تطبيق، وهذا أيضًا يفعّل RLS عليه.`,['roles']),

Q('security','single',3,'Semantic model access',
`A user with the Viewer role wants to use Analyze in Excel on a semantic model in the workspace, but the option is unavailable. What should you grant?`,
[`Build permission on the semantic model`,`The Admin role`,`Write permission on the report`,`A Pro license only`],0,
`Viewers need Build permission on the semantic model to use Analyze in Excel or export underlying data.`,
[``,`Admin is far more than needed.`,`Report write permission doesn't give model access for Excel.`,`A license alone doesn't grant the permission.`],
`Viewer يحتاج Build لاستخدام Analyze in Excel.`,['roles','build']),

Q('security','order',3,'RLS',
`You need dynamic row-level security so each store manager sees only their stores. Which three actions should you perform in sequence?`,
[`Load a mapping table of manager email to StoreID and relate it to the Store dimension`,`Create a role with the filter [ManagerEmail] = USERPRINCIPALNAME() on the mapping table, then test it with View as`,`Publish, then add the managers' security group to the role on the semantic model's Security page`,`Give managers the Contributor role`,`Hide the Store table`],
[0,1,2],
`Model the user-to-data mapping first, define and test the role, then publish and assign members in the service. Contributors would bypass RLS, and hiding tables isn't security.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`Contributors aren't restricted by RLS.`,`Hiding isn't security.`],
`الخطوات: جدول ربط، دور ديناميكي واختباره، ثم النشر وإضافة الأعضاء.`,['rls','rlsg']),

Q('security','single',2,'Item access',
`A user who isn't in the workspace received a link to an app report, but sees an access request page. The app was published to the Sales audience only. What should you do?`,
[`Add the user (or their group) to the app audience`,`Give them Build permission only`,`Add them to the RLS role only`,`Certify the report`],0,
`App access comes from the audiences configured when publishing the app. RLS and Build don't grant access to the app itself.`,
[``,`Build doesn't give app access.`,`RLS membership doesn't give app access.`,`Endorsement doesn't grant access.`],
`الوصول للتطبيق يُمنح عبر إضافة المستخدم إلى الـ audience.`,['apps'])
];
