// PL-300 bank, batch H: extra ordering and multiple-answer practice across the outline
const Q = require('./h.js');
module.exports = [
Q('get','order',2,'Shared semantic model',
`You need to add a local Excel table of budgets to a report that currently uses a live connection to a published semantic model. Which three actions should you perform in sequence?`,
[`Select Make changes to this model to switch to a DirectQuery connection to the semantic model`,`Get data from the Excel workbook and load the budget table`,`Create a relationship from the budget table to the model's Date table`,`Download the semantic model's .pbix and edit it`,`Change the semantic model's storage mode to Import in the service`],
[0,1,2],
`A live connection can't mix sources. Converting to a composite model (DirectQuery to the semantic model) allows adding local tables and relationships.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`That creates a separate copy of the model.`,`You can't change a published model's storage mode from a report.`],
`الخطوات: Make changes to this model ثم إضافة الجدول ثم إنشاء العلاقة.`,['composite']),

Q('clean','order',2,'Data quality',
`A Phone column has values with spaces, dashes and the country code in different formats. You need one consistent format. Which three actions should you perform in sequence in Power Query?`,
[`Trim the column and use Replace values to remove spaces and dashes`,`Add a conditional column (or custom column) that adds the country code when it's missing`,`Remove the original column and rename the new one to Phone`,`Change the Phone column type to Decimal Number`,`Pivot the Phone column`],
[0,1,2],
`Normalize the characters first, then apply the formatting rule, and finally replace the old column. Phone numbers are text, not numbers.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`Numbers lose leading zeros and the plus sign.`,`Pivot doesn't clean values.`],
`تنظيف الهاتف: إزالة المسافات والشرطات ثم توحيد كود الدولة ثم استبدال العمود.`,['types']),

Q('transform','multi',2,'Merge and append',
`You're combining data in Power Query. Which two statements are correct? Each correct answer presents a complete solution. Select TWO.`,
[`Append adds rows from tables with the same columns`,`Merge adds columns from another table by matching key values`,`Append requires a key column to match rows`,`Merge can only combine two tables that have identical columns`,`Append removes duplicate rows automatically`],
[0,1],
`Append stacks rows and matches columns by name. Merge joins tables on keys and adds columns. Append needs no key and doesn't remove duplicates.`,
[`Correct.`,`Correct.`,`Append matches by column name, not key.`,`Merge works on any tables with a matching key.`,`Duplicates stay unless you remove them.`],
`Append يضيف صفوفًا، وMerge يضيف أعمدة بمطابقة مفتاح.`,['append','merge']),

Q('design','order',2,'Date table',
`You need a proper Date table for time intelligence in a model that has no date table yet. Which three actions should you perform in sequence?`,
[`Create a table with a contiguous list of dates covering all years in the data (CALENDAR or Power Query List.Dates)`,`Add Year, Month, Month Number and other columns, and sort Month by Month Number`,`Mark it as a date table and relate its Date column to the fact tables' date columns`,`Turn on Auto date/time`,`Create a many-to-many relationship to Sales`],
[0,1,2],
`Build a complete date range, add the attributes users need with correct sorting, then mark it and relate it. Auto date/time isn't needed with a proper date table.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`Auto date/time adds hidden tables instead.`,`Date to Sales is one-to-many.`],
`الخطوات: قائمة تواريخ كاملة، ثم الأعمدة والترتيب، ثم Mark as date table والعلاقات.`,['markdate','datetbl']),

Q('dax','multi',3,'Time intelligence',
`Which two measures return sales for the previous month when used in a visual grouped by month? Each correct answer presents a complete solution. Select TWO.`,
[`CALCULATE([Sales], PREVIOUSMONTH('Date'[Date]))`,`CALCULATE([Sales], DATEADD('Date'[Date], -1, MONTH))`,`CALCULATE([Sales], SAMEPERIODLASTYEAR('Date'[Date]))`,`TOTALMTD([Sales], 'Date'[Date])`,`[Sales] - 30`],
[0,1],
`PREVIOUSMONTH returns the dates of the previous month, and DATEADD shifts the current dates back one month. SAMEPERIODLASTYEAR goes back a year, TOTALMTD is month to date and subtracting 30 isn't a time shift.`,
[`Correct.`,`Correct.`,`That's the same month last year.`,`That's month-to-date of the current month.`,`That subtracts 30 from the sales amount.`],
`الشهر السابق: PREVIOUSMONTH أو DATEADD بقيمة -1 MONTH.`,['ti']),

Q('dax','order',3,'Calculation groups',
`You need a Time Intelligence calculation group with Current, YTD and PY items in Power BI Desktop. Which three actions should you perform in sequence?`,
[`In Model view, select Calculation group and accept turning on Discourage implicit measures`,`Create calculation items such as YTD = CALCULATE(SELECTEDMEASURE(), DATESYTD('Date'[Date]))`,`Put the calculation group column on a matrix's columns and a measure in Values`,`Create a what-if parameter`,`Create an implicit SUM of Sales[Amount] in the matrix`],
[0,1,2],
`Create the group (which requires discouraging implicit measures), define items with SELECTEDMEASURE, then use the group's column in a visual with an explicit measure.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`What-if parameters are unrelated.`,`Calculation items don't apply to implicit measures.`],
`الخطوات: إنشاء المجموعة، ثم العناصر بـ SELECTEDMEASURE، ثم استخدامها في visual.`,['calcgrp']),

Q('perf','order',2,'Performance Analyzer',
`A report page is slow and you want to find and fix the slowest measure. Which three actions should you perform in sequence?`,
[`Open Performance Analyzer, start recording and refresh the visuals`,`Sort by duration and copy the query of the slowest visual`,`Paste it into DAX query view, test an improved measure with DEFINE MEASURE and update the model`,`Turn on Auto date/time`,`Add more visuals to compare`],
[0,1,2],
`Measure first, isolate the slowest query, then test and apply a fix in DAX query view.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`That adds hidden tables and doesn't help.`,`More visuals add load.`],
`الخطوات: تسجيل Performance Analyzer، نسخ أبطأ استعلام، ثم تحسينه في DAX query view.`,['perfan','daxqv']),

Q('reports','multi',2,'Choose a visual',
`Which two visuals are good choices to compare the sales of 12 product categories at one point in time? Each correct answer presents a complete solution. Select TWO.`,
[`Clustered bar chart`,`Clustered column chart`,`Line chart`,`Pie chart with 12 slices`,`Card`],
[0,1],
`Bars and columns make it easy to compare category sizes. Lines imply continuity over time, pies with many slices are hard to compare and cards show one value.`,
[`Correct.`,`Correct.`,`Lines are for trends.`,`Twelve slices are hard to compare.`,`Cards show one number.`],
`للمقارنة بين فئات كثيرة: Bar أو Column chart.`,['visuals']),

Q('usability','order',2,'Bookmarks',
`You need buttons that switch a page between a map view and a table view. Which three actions should you perform in sequence?`,
[`Place both visuals on the page and use the Selection pane to hide the table`,`Create a bookmark MapView, then show the table and hide the map, and create a bookmark TableView`,`Add two buttons with the Bookmark action set to MapView and TableView`,`Create a drillthrough page`,`Turn on Personalize visuals`],
[0,1,2],
`Visibility is set in the Selection pane, captured in bookmarks (Display state) and triggered by buttons.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`Drillthrough navigates to another page.`,`Personalization isn't needed.`],
`الخطوات: Selection pane للإخفاء، ثم Bookmarks لكل حالة، ثم أزرار.`,['bookmarks','buttons']),

Q('patterns','order',2,'Grouping and binning',
`You need a histogram of order amounts in bands of 100. Which three actions should you perform in sequence?`,
[`Right-click the Amount column and select New group`,`Choose Bin as the group type and set the bin size to 100`,`Put the new bin column on the axis of a column chart and a count of orders in Values`,`Add Amount to a slicer`,`Create a Top N filter`],
[0,1,2],
`Binning creates a new column with equal-size ranges that you use as the chart axis.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`A slicer doesn't create bands.`,`Top N limits items.`],
`الخطوات: New group ثم Bin بحجم 100 ثم وضعه على المحور.`,['grouping']),

Q('workspace','order',2,'Apps',
`You need to distribute a workspace's reports to the sales team as an app and update it later. Which three actions should you perform in sequence?`,
[`Select Create app in the workspace and choose the content and navigation`,`Configure an audience with the sales team's security group and publish the app`,`After changing a report, select Update app`,`Add every salesperson as a workspace Contributor`,`Share the .pbix file by email`],
[0,1,2],
`Create the app from the workspace, set audiences and publish, then update the app when content changes.`,
[`Step 1.`,`Step 2.`,`Step 3.`,`Contributors could edit content.`,`Emailing files breaks governance.`],
`الخطوات: Create app ثم audience والنشر ثم Update app بعد التعديلات.`,['apps']),

Q('security','multi',2,'Sensitivity labels',
`Which two export formats keep a Power BI sensitivity label and its protection? Each correct answer presents a complete solution. Select TWO.`,
[`Excel (.xlsx)`,`PDF`,`CSV`,`A screenshot image`,`Copying values to the clipboard`],
[0,1],
`Sensitivity labels are applied to supported exported files such as Excel, PowerPoint and PDF. CSV, images and clipboard copies don't carry labels.`,
[`Correct.`,`Correct.`,`CSV doesn't support sensitivity labels.`,`Images don't carry labels.`,`Clipboard content isn't labeled.`],
`التصنيف ينتقل مع Excel وPowerPoint وPDF، وليس مع CSV.`,['labels','export']),

Q('security','multi',3,'Workspace roles',
`Which two workspace roles can publish the workspace app and add users to the workspace? Each correct answer presents a complete solution. Select TWO.`,
[`Admin`,`Member`,`Contributor`,`Viewer`,`Any user with Build permission`],
[0,1],
`Admins and Members can publish or unpublish the app and add users (Members can add roles up to Member). Contributors can only update the app when allowed, and Viewers read content.`,
[`Correct.`,`Correct.`,`Contributors can't publish the app or add users.`,`Viewers only view.`,`Build permission is for building content.`],
`نشر التطبيق وإضافة المستخدمين: Admin وMember.`,['roles'])
];
